apps/platform/src/pages/HomePage/searchExamples.js
=> Disease IDs needed to be updated do to EFO change

apps/platform/src/pages/APIPage/APIPage.jsx
Issue: https://github.com/opentargets/issues/issues/2636
=> fix(platform): API page crash on load

apps/platform/src/pages/DiseasePage/ClassicAssociationsTable.jsx, apps/platform/src/pages/TargetPage/ClassicAssociationsTable.jsx, apps/platform/src/sections/evidence/OTEncore/Body.jsx
Short PR to include the latest PPP changes
=> Lf ppp updates

apps/platform/src/components/Table/TablePaginationActions.jsx
Issue: https://github.com/opentargets/issues/issues/2643
=> bug(Platform): Page handlers not working on the platform-app table component

apps/platform/src/sections/evidence/GeneBurden/Body.jsx, apps/platform/src/sections/evidence/GeneBurden/Description.jsx, apps/platform/src/sections/evidence/GeneBurden/GeneBurdenQuery.gql
Issue: https://github.com/opentargets/issues/issues/2635
Deploy preview: https://deploy-preview-13--ot-platform.netlify.app/
=> feat(Platform): add field and adjust sources in gene burden table

apps/platform/package.json, apps/platform/src/sections/target/SubcellularLocation/Body.jsx, apps/platform/src/sections/target/SubcellularLocation/SubcellularLocation.gql, apps/platform/src/sections/target/SubcellularLocation/SubcellularViz.jsx, apps/platform/src/sections/target/SubcellularLocation/SwissbioViz.jsx, yarn.lock
This PR adds swissbiopic visualisation to subcellular location widget. 
Details: https://github.com/opentargets/issues/issues/1875
The implementation follows Uniprot / Swissprot approaches
=> Lf swissbiopic

apps/genetics/src/config.js
Update API config URL to https://api.genetics.dev.opentargets.xyz/graphql
=> feat(genetics): update api URL

apps/genetics/src/pages/StudyLocusPage/StudyLocusPage.jsx, apps/genetics/src/queries/StudyLocusPageQuery.gql, apps/genetics/src/sections/studyLocus/Summary/Summary.jsx, apps/genetics/src/utils/common.js, apps/genetics/src/utils/index.js, apps/genetics/src/utils/studyLocus.js
1. Study locus summary component moved to be a separate component
2. Added skeleton component for handling loading state of component
3. Part of issue#: https://github.com/opentargets/issues/issues/2662
=> summary component restructure study locus

apps/genetics/src/pages/StudyLocusPage/StudyLocusPage.jsx, apps/genetics/src/queries/StudyLocusPageQuery.gql, apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.gql, apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx, apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/index.js
[x] Made a separate section under study locus page for Genes Prioritisation Tabs from page component.
[x] Gene Prioritisation Tabs section component take input for making separate gql call.
[x] Added Skeleton for loading state.
[x] Part of issue #: https://github.com/opentargets/issues/issues/2662
=> gene prioritisation component tabs

apps/genetics/src/ot-ui-components/components/DataDownloader.jsx, apps/genetics/src/pages/StudyLocusPage/StudyLocusPage.jsx, apps/genetics/src/queries/StudyLocusPageQuery.gql, apps/genetics/src/sections/studyLocus/ColocGWASTable/ColocGWASTable.jsx, apps/genetics/src/sections/studyLocus/ColocGWASTable/StudyLocusColocGWASTable.gql, apps/genetics/src/sections/studyLocus/ColocGWASTable/index.js, apps/genetics/src/sections/studyLocus/ColocL2GTable/ColocL2GTable.jsx, apps/genetics/src/sections/studyLocus/ColocL2GTable/StudyLocusColocL2GTable.gql, apps/genetics/src/sections/studyLocus/ColocL2GTable/index.js, apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.gql, apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/GenePrioritisationTabs.jsx, apps/genetics/src/sections/studyLocus/GenePrioritisationTabs/index.js, apps/genetics/src/sections/studyLocus/Genes/StudyLocusGenes.jsx, apps/genetics/src/sections/studyLocus/Genes/StudyLocusGenesQuery.gql, apps/genetics/src/sections/studyLocus/Genes/index.js, apps/genetics/src/utils/common.js
[x] Made a separate section under study locus page for coloc l2g table instead of component.
[x] Added loading state in DataDownloader component through mui skeleton.  
[x]  Coloc l2g table component take input for making separate gql call.
[x] Part of issue #: https://github.com/opentargets/issues/issues/2662
=> coloc l2g table component

apps/genetics/src/components/ColocQTLGeneTissueTable/ColumnRenderers.jsx, apps/genetics/src/components/ColocQTLGeneTissueTable/useColocTable.js
- update style remove phenotypeId from unique
=> remove phenotypeid

apps/genetics/src/components/ColocForGeneTable/ColocForGeneTable.jsx, apps/genetics/src/components/ColocForGeneTable/ColumnRederers.jsx, apps/genetics/src/components/ColocForGeneTable/index.js, apps/genetics/src/components/ColocQTLGeneTissueTable/useColocTable.js, apps/genetics/src/components/ColocQTLGeneTissueTable/utils.js, apps/genetics/src/pages/StudyLocusPage/StudyLocusPage.jsx, apps/genetics/src/utils/index.js
call phenotype util from gene page and study locus table
reformat ColocForGeneTable
=> Remove cluster from phenotype

apps/platform/src/components/RoutingTabs/RoutingTabs.jsx, apps/platform/src/pages/APIPage/APIPage.jsx, apps/platform/src/pages/APIPage/APIPageWrapper.jsx, apps/platform/src/pages/DownloadsPage/DownloadsWrapper.jsx, apps/platform/src/pages/EvidencePage/EvidencePage.jsx, apps/platform/src/pages/SearchPage/SearchPage.jsx, apps/platform/src/pages/TargetPage/TargetPage.jsx, apps/platform/src/pages/VariantsPage/VariantsWrapper.jsx, apps/platform/src/sections/target/SubcellularLocation/SubcellularViz.jsx, packages/ui/index.js, packages/ui/src/LoadingBackdrop.jsx
[x] Loading component added to ui package.
[x] Loading component removed from platform code.
[x] Height css modified to take parent height of loading component.
[x] Part of issue: https://github.com/opentargets/issues/issues/2707
=> Loading backdrop component added to ui package

apps/genetics/src/pages/VariantPage/Header.jsx, apps/genetics/src/pages/VariantPage/VariantHeader.gql, apps/genetics/src/sections/variant/PheWASSection/PheWASSection.jsx
=> Update Links Variant Page

apps/genetics/src/components/ColocForGeneTable/ColumnRederers.jsx
Soves https://github.com/opentargets/issues/issues/2708
Update column header and add tooltip
=> Update molecular trait column gene page

apps/platform/src/pages/DrugPage/Smiles.jsx
Very short PR to remove border and background from drug structure image as per issue https://github.com/opentargets/issues/issues/1558
=> Remove background and border from drug page structure image

apps/platform/src/components/PrivateWrapper.jsx, apps/platform/src/hooks/usePermissions.js, apps/platform/src/pages/DiseasePage/ClassicAssociationsTable.jsx, apps/platform/src/pages/HomePage/HomePage.jsx, apps/platform/src/pages/HomePage/index.jsx, apps/platform/src/pages/TargetPage/ClassicAssociationsTable.jsx
[x] Wrapper component added to add content when partner preview config is true.
[x] Custom hook added which return partner preview config.
[x] Reference in homepage, classicAssociationTable, index updated.
[x] Part of Issue: https://github.com/opentargets/issues/issues/2714
=> Permissions component added 

apps/genetics/src/pages/GenePage/GenePage.jsx, apps/genetics/src/sections/gene/ColocAnalysis/ColocAnalysis.jsx, apps/genetics/src/sections/gene/ColocAnalysis/ColocAnalysisQuery.gql, apps/genetics/src/sections/gene/ColocAnalysis/index.js, apps/genetics/src/sections/gene/L2GPipeline/L2GPipeline.jsx, apps/genetics/src/sections/gene/L2GPipeline/L2GPipelineQuery.gql, apps/genetics/src/sections/gene/L2GPipeline/index.js
[x]. Coloc analysis component section added.
[x]. Separate gql query added.
[x]. Loading state added.
[x]. Part of Issue : [Issue Gene Page](https://github.com/opentargets/issues/issues/2696)
=> Gene coloc analysis section

apps/genetics/src/sections/variant/PheWASSection/ForestPlot.jsx, apps/genetics/src/sections/variant/PheWASSection/PheWASSection.jsx
This PR updates the styling of the title and sub title for the Forest plot.
see: https://github.com/opentargets/issues/issues/2667
=> update styling of title and subtitle

apps/genetics/src/components/ColocForGeneTable/ColocForGeneTable.jsx
[x] Colocalisation analysis table sort column preference updated.
[x] Fix of issue: https://github.com/opentargets/issues/issues/2729
=> coloc for gene table sort column updated

apps/genetics/index.html
To compare: https://github.com/opentargets/genetics-app/blob/main/public/index.html
=> [fix]: Genetics meta tags

apps/platform/src/sections/evidence/OTCRISPR/Body.jsx
Issue: https://github.com/opentargets/issues/issues/2724
=> [PPP]: OT-Crispr - fix parsing of Significance column 

apps/platform/src/sections/common/Literature/Body.jsx, apps/platform/src/sections/common/Literature/DateFilter.jsx, apps/platform/src/sections/common/Literature/atoms.js, apps/platform/src/sections/disease/Bibliography/BibliographyQuery.gql, apps/platform/src/sections/drug/Bibliography/BibliographyQuery.gql, apps/platform/src/sections/target/Bibliography/SimilarEntities.gql
solves https://github.com/opentargets/issues/issues/2578
include date filter for bibliography
update query to handle start and end date
=> Filter biobliography results by publication date

apps/platform/src/components/AssociationsToolkit/prioritisation/prioritizationCols.js
Added new column names and revised version of others
=> Jm colnames

apps/platform/src/sections/common/Literature/Body.jsx
=> Hide date filter in Literature

apps/platform/src/pages/ProjectsPage/ProjectsPage.jsx, apps/platform/src/pages/ProjectsPage/projects-data.json
PPP projects page and table content updated
=> PPP projects page and table content updated

apps/platform/src/sections/target/Safety/Safety.gql, apps/platform/src/sections/target/Safety/SafetyTable.jsx
issue: https://github.com/opentargets/issues/issues/2837
=> [Target]: fix Safety component

apps/platform/index.html, apps/platform/src/App.jsx, apps/platform/src/components/PrivateRoute.jsx, apps/platform/src/config.js, apps/platform/src/constants.js, apps/platform/src/pages/ProjectsPage/ProjectsPage.jsx, apps/platform/src/pages/ProjectsPage/ProjectsPageWrapper.jsx, apps/platform/src/pages/ProjectsPage/index.js, apps/platform/src/pages/ProjectsPage/projects-data.json
Issue reference: https://github.com/opentargets/issues/issues/2853
=> PPP: Projects page

apps/platform/src/sections/evidence/Gene2Phenotype/Body.jsx, apps/platform/src/sections/evidence/Gene2Phenotype/sectionQuery.gql, apps/platform/src/sections/evidence/GenomicsEngland/Body.jsx, apps/platform/src/sections/evidence/GenomicsEngland/sectionQuery.gql
issue: https://github.com/opentargets/issues/issues/2750
=> [Platform]: Fix Gene2Phenotype and CellPanel tables sizes

apps/platform/src/App.jsx, apps/platform/src/pages/HomePage/HomePage.jsx, apps/platform/src/pages/HomePage/PPHomePage.jsx, packages/ui/src/AutocompleteSearch.jsx, packages/ui/src/GlobalSearch.jsx, packages/ui/src/Search/SearchContext.jsx, packages/ui/src/Search/SearchListHeader.jsx, packages/ui/src/Search/SearchRecentListItem.jsx, packages/ui/src/utils/searchUtils.js
issue: https://github.com/opentargets/issues/issues/2765
**note:** displaying only ppp profile, no data.
=> [Platform]: Global search ui fixes

apps/platform/src/components/PublicationsDrawer/PublicationWrapper.jsx, apps/platform/src/sections/common/Literature/atoms.js, apps/platform/src/utils/urls.js
issue: https://github.com/opentargets/issues/issues/2881
=> [Platform]: handle patents in the literature section

apps/platform/index.html, apps/platform/src/pages/ProjectsPage/ProjectsPage.jsx, apps/platform/src/pages/ProjectsPage/projects-data.json
**Issue:** # https://github.com/opentargets/issues/issues/2889
**Deploy preview:** https://deploy-preview-99--ot-platform.netlify.app/
=> [Platform]: PPP projects data update

apps/platform/index.html, apps/platform/src/config.js
=> [Platform]: revert config

packages/ui/src/AutocompleteSearch.tsx, packages/ui/src/Footer.tsx, packages/ui/src/GlobalSearch.tsx, packages/ui/src/LoadingBackdrop.tsx, packages/ui/src/Search/SearchContext.tsx, packages/ui/src/Search/SearchInput.tsx, packages/ui/src/Search/SearchListItem.tsx, packages/ui/src/ThemeProvider/ThemeProvider.tsx, packages/ui/src/ThemeProvider/defaultTheme.ts, packages/ui/src/utils/searchUtils.ts
**Issue:**  [task#2-of-issue-2871](https://github.com/opentargets/issues/issues/2871)
* Breaking change (fix or feature that would cause existing functionality to not work as expected)
* Test A : navigate to ot-ui-apps and run ```yarn lint```
=> [Package]: UI lint errors fixed

apps/platform/src/components/AssociationsToolkit/HeaderControls/HeaderControls.jsx, apps/platform/src/components/AssociationsToolkit/Table/TableAssociations.jsx, apps/platform/src/components/AssociationsToolkit/static_datasets/dataSourcesAssoc.js, apps/platform/src/components/AssociationsToolkit/style.css
Not tested modification to include encore as a datasource in the AOTF view (it was commented out before)
=> [Platform]: add encore column to AOTF

apps/platform/src/sections/common/KnownDrugs/Body.jsx
**Issue:** # (not-created)
**Deploy preview:** [platform-preview-link](https://deploy-preview-130--ot-platform.netlify.app/target/ENSG00000169174)
* Test A : Go to [platform](https://platform.opentargets.org/target/ENSG00000169174) scroll to known drugs and click on phase header to sort. It does not sort the data.
* Test B : Go to [preview-link](https://deploy-preview-130--ot-platform.netlify.app/target/ENSG00000169174) scroll to known drugs and click on phase header to sort. It sorts the data.
=> [Platform]: Sort handler function added for know drugs common section

apps/genetics/package.json, apps/genetics/src/components/Link.tsx, apps/genetics/src/ot-ui-components/components/Link.tsx, yarn.lock
Should match thease format: [Scoped application (Genetics || Platform || Package || AppConfig)]: Short description mentioning the affected page and/or section component
**Issue:** #[(2871](https://github.com/opentargets/issues/issues/2871)
PR change is recommended by react: https://react.dev/reference/react/Component#static-proptypes
=> [Genetics] Update Link component props to use ts types

apps/genetics/src/ot-ui-components/components/ModelSchematic.tsx, apps/genetics/src/ot-ui-components/components/SectionHeading.tsx
Use a proper structure for the model entity type basically, by dynamically generating the type from the nicename map.
**Issue:** #[2871](https://github.com/opentargets/issues/issues/2871)
Refactor (non-breaking change)
manual
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] Any dependent changes have been merged and published in downstream modules
=> [Genetics] Fix types on modelschematic and sectionheading where its used

apps/platform/public/Unauthorised.html, apps/platform/public/Unauthorized.html
**Issue:** # [issue-2938](https://github.com/opentargets/issues/issues/2938)
**Deploy preview:** [ppp-403](https://deploy-preview-141--ot-platform-partner.netlify.app/unauthorised)
* New feature (non-breaking change which adds functionality)
* Test: Open [ppp](https://partner-platform.opentargets.org/) outside permitted network. Custom html should be shown instead of default "Forbidden 403" message from browser.
=> [Plaform]: Unauthorized.html for PPP

.travis.yml
The deployment process on Travis is failing with this issue:
```
platform:build: FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```
- Trasvis deploy check should be success ✅
=> [AppConfig]: Travis deployment config fix

apps/platform/src/components/ShouldAccessPPP.tsx
* Test: Just text update, nothing to text.
=> [Platform]: PPP popup text update

apps/platform/src/sections/disease/Phenotypes/Body.jsx
**Issue:** # [issue-2972](https://github.com/opentargets/issues/issues/2972)
**Deploy preview:** https://deploy-preview-150--ot-platform.netlify.app/disease/EFO_0000756
- Test A: crashing url : https://platform.mbdev.opentargets.xyz/disease/EFO_0000756
- Test B: working url:  https://deploy-preview-150--ot-platform.netlify.app/disease/EFO_0000756
=> [Platform]: Clinical signs and symptoms widget crashing fix

apps/platform/src/components/ShouldAccessPPP.tsx
**Issue:** # [2967](https://github.com/opentargets/issues/issues/2967)
**Deploy preview:** https://deploy-preview-153--ot-platform.netlify.app/
* Test A: popup should not come before 14 days of "remind me later"
=> [Platform]: PPP popup 14 days limit

apps/platform/src/sections/common/KnownDrugs/Body.jsx
Bug on Know drugs section pagination 
**Deploy preview:** https://deploy-preview-157--ot-platform.netlify.app/disease/EFO_0003843
- Check on Know drugs pagination  https://deploy-preview-157--ot-platform.netlify.app/disease/EFO_0003843
=> [Platform]: Know drugs pagination bug

apps/platform/src/sections/drug/DrugWarnings/Body.jsx, apps/platform/src/sections/drug/DrugWarnings/DrugWarningsQuery.gql
**Issue:** # [2943](https://github.com/opentargets/issues/issues/2943)
**Deploy preview:** https://deploy-preview-155--ot-platform.netlify.app/
* Test A : New column and link to warning column added in drug warning table.
=> [Platform]: Update drugWarnings annotation in the Platform

apps/platform/src/pages/APIPage/TargetAnnotation.gql
**Issue:** # [2985](https://github.com/opentargets/issues/issues/2985)
* Test A:
1. Go to API playground page
2. Run Target annotation sample query
=> [Platform]: Updated sample target annotation crashing query

apps/platform/src/constants.js, apps/platform/src/pages/DrugPage/ProfileHeader.jsx, apps/platform/src/sections/common/KnownDrugs/Body.jsx, apps/platform/src/sections/drug/Indications/Body.jsx, apps/platform/src/sections/evidence/Chembl/Body.jsx
**Issue:** # https://github.com/opentargets/issues/issues/2969
- check on [/evidence/ENSG00000093010/EFO_0007046](https://platform.dev.opentargets.xyz/evidence/ENSG00000093010/EFO_0007046)
=> [Platform]: Update clinicalPhases map 

apps/platform/src/pages/APIPage/DiseaseAnnotation.gql, apps/platform/src/sections/target/Tractability/TractabilityQuery.gql, apps/platform/src/sections/target/Tractability/TractabilitySummary.gql
**Issue:** # [2988](https://github.com/opentargets/issues/issues/2988)
**Deploy preview:** https://deploy-preview-171--ot-platform.netlify.app/target/ENSG00000157404
=> [Platform]: Tractability label update and sample query fix

apps/platform/src/components/Table/DataTable.jsx, apps/platform/src/sections/common/Literature/Body.jsx, apps/platform/src/sections/common/Literature/PublicationsList.jsx
**Issue:** # https://github.com/opentargets/issues/issues/2998
=> [Platform]: Rows per page change function

apps/platform/src/utils/urls.js
**Issue:** # [(link)](https://github.com/opentargets/issues/issues/2995)
=> [Platform]: Publication drawer request handle preprints

apps/platform/src/sections/evidence/EuropePmc/Body.jsx
**Deploy preview:** https://deploy-preview-181--ot-platform.netlify.app/evidence/ENSG00000142192/MONDO_0004975
=> [Platform]: Evidence epmc rows per page fix

apps/platform/src/pages/ProjectsPage/ProjectsPage.jsx, apps/platform/src/pages/ProjectsPage/projects-data.json
=> [Platform]: projects table data update

apps/platform/src/pages/TargetPage/ProfileHeader.jsx, apps/platform/src/pages/TargetPage/TargetDescription.jsx
As per title, this PR fixes the "core essential gene" chip that didn't display for targets with missing description, i.e. essential genes that don't have a description (not a common occurrence).
The chip is refactored out of the TargetDescription component.
**Issue:** no issue available
**Deploy preview:** https://deploy-preview-187--ot-platform.netlify.app
=> [Platform]: fix "core essential gene" chip display for targets with missing description

apps/platform/src/components/ChipList.jsx, apps/platform/src/components/ExternalLink/CrisprDepmapLink.jsx, apps/platform/src/components/ExternalLink/TepLink.jsx, apps/platform/src/components/LabelChip.jsx, apps/platform/src/components/ProfileHeader/ChipList.jsx, apps/platform/src/components/Tooltip.jsx, apps/platform/src/pages/TargetPage/AssociationTooltip.jsx, apps/platform/src/sections/evidence/GenomicsEngland/Body.jsx, apps/platform/src/theme.js, packages/sections/src/components/ChipList.jsx, packages/sections/src/components/ExternalLink/CrisprDepmapLink.jsx, packages/sections/src/components/ExternalLink/TepLink.jsx, packages/sections/src/components/ProfileHeader/ChipList.jsx, packages/sections/src/components/Tooltip.jsx, packages/sections/src/evidence/GenomicsEngland/Body.jsx, packages/ui/src/components/AutocompleteSearch.tsx, packages/ui/src/components/Chip.jsx, packages/ui/src/components/ChipList.jsx, packages/ui/src/components/ErrorBoundary.jsx, packages/ui/src/components/Footer.tsx, packages/ui/src/components/GlobalSearch.tsx, packages/ui/src/components/LoadingBackdrop.tsx, packages/ui/src/components/LongText.tsx, packages/ui/src/components/NavPanel/SectionMenuItem.jsx, packages/ui/src/components/Search/SearchInput.tsx, packages/ui/src/components/Search/SearchListHeader.tsx, packages/ui/src/components/Search/SearchListItem.tsx, packages/ui/src/components/Search/SearchRecentListItem.tsx, packages/ui/src/components/Tooltip.jsx
Should match thease format: [Scoped application (Genetics || Platform || Package || AppConfig)]: Short description mentioning the affected page and/or section component
=> Cm migrate mui5

apps/genetics/public/profiles/default.js, apps/genetics/src/pages/NotFoundPage/NotFoundPage.jsx, apps/platform/public/profiles/default.js, apps/platform/public/profiles/partners.js, apps/platform/src/pages/NotFoundPage/NotFoundPage.jsx, apps/platform/src/pages/SearchPage/SearchPage.jsx, packages/ui/src/pages/EmptyPage.tsx
**Issue:** # [2903](https://github.com/opentargets/issues/issues/2903)
**Deploy preview:**  https://deploy-preview-185--ot-platform.netlify.app/s
=> [Platform]: 404 links updated

apps/platform/src/pages/DrugPage/Smiles/SmilesHelper.jsx
=> [Platform]: Smiles parsing error fixed

packages/sections/src/target/Safety/SafetyStudiesDrawer.jsx
=> [Platform]: Updated button to link for studies column in safety widget 

packages/ui/src/components/Section/SectionItem.jsx, packages/ui/src/components/Summary/SummaryItem.jsx
=> [Platform]: mui5 style fixes

apps/platform/src/pages/DiseasePage/DiseasePage.jsx, apps/platform/src/pages/DrugPage/DrugPage.jsx, apps/platform/src/pages/TargetPage/TargetPage.jsx
=> [Platform]: Active routing tabs and capital case fix

packages/sections/src/disease/Phenotypes/Body.jsx
=> [Platform]: updated section item import component to package

.travis.yml
Should match thease format: [Scoped application (Genetics || Platform || Package || AppConfig)]: Short description mentioning the affected page and/or section component
=> [AppConfig]: travis config

packages/sections/src/components/Table/Table.jsx, packages/sections/src/evidence/EuropePmc/Body.jsx, packages/ui/src/components/icons/ArrowTurnDownLeft.tsx
=> [Platform]: europepmc loading

apps/platform/src/components/AssociationsToolkit/Table/CellName.jsx, apps/platform/src/components/AssociationsToolkit/TargetPrioritisationSwitch.jsx, apps/platform/src/components/AssociationsToolkit/utils/index.js, apps/platform/src/components/NavBar.jsx, apps/platform/src/pages/TargetPage/Header.jsx, apps/platform/src/theme.js, packages/ui/src/ThemeProvider/ThemeProvider.tsx
=> [Platform]: fix font size and button color

apps/platform/src/components/ShouldAccessPPP.tsx, packages/sections/src/common/KnownDrugs/SourceDrawer.jsx, packages/ui/src/components/Search/SearchListHeader.tsx, packages/ui/src/components/Section/SectionItem.jsx, packages/ui/src/pages/Page.tsx
=> [Platform]: button, text and padding update

apps/platform/src/pages/HomePage/HomePage.jsx
=> [Platform]: home page suggestion font and duplicate bug

packages/ui/src/components/Tooltip.jsx
Fix the tooltip styles as these were not being applied. It should now be the same as in production.
The background is still a little transparent (same as before, MUI default) - @prashantuniyal02 as you picked up the issue, does this solution work for you?
**Issue:** N/A
**Deploy preview:** https://deploy-preview-229--ot-platform.netlify.app/
=> [Platform]: fix tooltip styles

apps/platform/src/components/AssociationsToolkit/AdvanceOptionsMenu.jsx, apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx, apps/platform/src/components/AssociationsToolkit/Table/CellName.jsx, apps/platform/src/components/AssociationsToolkit/Table/TableBody.jsx, apps/platform/src/components/AssociationsToolkit/TargetPrioritisationSwitch.jsx, apps/platform/src/components/AssociationsToolkit/layout.jsx, apps/platform/src/pages/APIPage/APIPage.jsx, apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.jsx, apps/platform/src/pages/HomePage/Version.jsx, apps/platform/src/theme.js, packages/sections/src/target/MousePhenotypes/AllelicCompositionDrawer.jsx, packages/ui/src/components/Section/SectionItem.jsx, packages/ui/src/components/Summary/SummaryItem.jsx, packages/ui/src/components/Tooltip.jsx
**Issue:**  https://github.com/opentargets/issues/issues/3064 https://github.com/opentargets/issues/issues/3063
=> [Platform]: multiple styles updates

README.md
Should match thease format: [Scoped application (Genetics || Platform || Package || AppConfig)]: Short description mentioning the affected page and/or section component
documentation only about node version
None, no code changes
=> [Package] docs: update docs to reflect required node version in package.json

apps/platform/src/pages/DownloadsPage/DownloadsPage.jsx
#[Platform]: download sorted chips
=> [Platform]: download sorted chips

apps/platform/src/components/AssociationsToolkit/static_datasets/prioritizationCols.js, apps/platform/src/components/AssociationsToolkit/utils/index.js, packages/ui/src/components/PartnerLockIcon.jsx
**Issue:** # https://github.com/opentargets/issues/issues/3050 https://github.com/opentargets/issues/issues/3011
- Check associations section
=> [Platform]: add prioritisation columns and labels

apps/platform/src/pages/HomePage/PPHomePage.jsx
=> [Platform]: PPP Home page duplicate

apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx
**Issue:** https://github.com/opentargets/issues/issues/2958
**Deploy preview:** https://deploy-preview-255--ot-platform-partner.netlify.app/disease/MONDO_0010178/associations
- Check exporting a file from any disease associations page
=> [Platform]: prioritisation to disease assoc export on ppp

packages/sections/src/disease/OTProjects/Body.jsx, packages/sections/src/disease/OTProjects/Description.jsx, packages/sections/src/evidence/OTEncore/Description.jsx
=> [Platform]: fix typo and OTProejcts section

apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx, apps/platform/src/components/AssociationsToolkit/hooks/useBatchDownloader.js
Export (download) AotF data is breaking the UI
**Issue:** # https://github.com/opentargets/issues/issues/3063
- Check downloads on long associations list
=> [Platform]: AotF serialized download

apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx, packages/ui/src/components/PublicationsDrawer/SummaryLoader.jsx
=> [Platform]: Loading text updated

packages/ui/src/components/Chip.tsx
Migrate the Chip component to TypeScript.
=> [Package]: migrate Chip component to TypeScript

packages/sections/src/evidence/EuropePmc/Body.jsx
EuropePmc data download buttons did not work because no `dataDownloaderRows` were provided to the `<Table>` component.
In this PR, the `getDownloadData` function for `dataDownloaderRows` is provided. Additionally, the `europePmcId` and `pmcId` columns are added to the download data for reference.
The getDownloadData is required to fetch all literature data instead of just the data that is visible in the table.
Download EuropePmc data before and after fix by using `yarn dev: platform` and pointing to `"https://api.platform.opentargets.org/api/v4/graphql"` in the `config.js`
Downloading of data was tested on: …
=> Fix EuropePmc data download

README.md
=> [AppConfig]: update readme

apps/platform/src/client.js, packages/sections/src/client.js, packages/ui/src/client.js
- Check the target and disease page
=> [Platform]: Drug and Target page crashing do to apollo cache

packages/ui/src/components/OpenTargetsTitle.tsx
Migrate the OpenTargetsTitle component to TypeScript.
=> [Package]: migrate OpenTargetsTitle component to TypeScript

packages/ui/src/components/ClinvarStars.tsx
Migrate the ClinvarStars component to TypeScript.
=> [Package]: migrate ClinvarStars component to TypeScript

packages/ui/src/components/Legend.tsx
Migrate the Legend component to TypeScript.
=> [Package]: migrate Legend component to TypeScript

packages/sections/src/evidence/OTCRISPR/Body.jsx, packages/sections/src/evidence/OTCRISPR/OTCrisprQuery.gql, packages/sections/src/evidence/OTEncore/Body.jsx, packages/sections/src/evidence/OTEncore/OTEncoreQuery.gql, packages/sections/src/evidence/OTValidation/Body.jsx, packages/sections/src/evidence/OTValidation/OTValidationQuery.gql
**Issue:** https://github.com/opentargets/issues/issues/3139
**Deploy preview:** https://deploy-preview-287--ot-platform-partner.netlify.app/
- Check PPP evidence sections
=> [Platform]: PPP Sections widgets default size query parameter

apps/platform/src/pages/DownloadsPage/dataset-mappings.json
Please review pharmacogenomics dataset addition
=> [Platform]: Pharmacogenomics - update dataset-mappings.json

packages/sections/src/drug/Pharmacogenomics/Body.jsx, packages/sections/src/target/Pharmacogenomics/PharmacogenomicsTable.jsx
**Issue:** # https://github.com/opentargets/issues/issues/3113
=> [Platform]: tooltip and color chip fix

packages/sections/src/drug/Pharmacogenomics/Body.jsx, packages/sections/src/target/Pharmacogenomics/Description.jsx, packages/sections/src/target/Pharmacogenomics/PharmacogenomicsTable.jsx
**Issue:** # https://github.com/opentargets/issues/issues/3113#issuecomment-1821189430
=> [Platform]: Pharmgbk widget crash

apps/platform/src/components/AssociationsToolkit/utils/downloads.js, packages/ui/src/hooks/useStateParams.ts
=> [Platform]: ispinned field fix

apps/platform/package.json, apps/platform/src/components/AssociationsToolkit/AdvanceOptionsMenu.jsx, apps/platform/src/components/AssociationsToolkit/CopyUrlButton.jsx, apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx, apps/platform/src/components/AssociationsToolkit/DataUploader/DataUploader.jsx, apps/platform/src/components/AssociationsToolkit/DataUploader/NestedItem.jsx, apps/platform/src/components/AssociationsToolkit/DataUploader/ValidationQuery.gql, apps/platform/src/components/AssociationsToolkit/DataUploader/index.js, apps/platform/src/components/AssociationsToolkit/index.js, apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.jsx, apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociations.jsx, yarn.lock
**Issue:** https://github.com/opentargets/issues/issues/2913
- Check a disease associations
=> [Platform]: AotF upload list of entities

packages/ui/src/hooks/useStateParams.ts
=> [Platform]: initial state in case of null param

apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx, apps/platform/src/components/AssociationsToolkit/DataUploader/DataUploader.jsx, apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.jsx, apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociations.jsx
=> [Platform]: AOTF export file and header text update

apps/platform/package.json, apps/platform/src/components/AssociationsToolkit/DataUploader/DataUploader.jsx, apps/platform/src/index.jsx, apps/platform/src/theme.js, yarn.lock
- Check suggestion on PPP preview
=> [Platform]: Upload suggestions component

packages/ui/src/components/NewChip.tsx
Migrate the NewChip component to TypeScript.
=> [Package]: migrate NewChip component to TypeScript

packages/sections/src/common/Literature/Body.jsx, packages/sections/src/common/Literature/Category.jsx, packages/sections/src/common/Literature/CountInfo.jsx, packages/sections/src/common/Literature/DateFilter.jsx, packages/sections/src/common/Literature/DateFilter.tsx, packages/sections/src/common/Literature/atoms.ts
**Issue:** # [2578](https://github.com/opentargets/issues/issues/2578)
=> [Platform]: Add literature date filter

apps/platform/package.json, apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx, apps/platform/src/components/AssociationsToolkit/DataUploader/DataUploader.jsx, apps/platform/src/components/AssociationsToolkit/DataUploader/NestedItem.jsx, yarn.lock
**Issue:** # https://github.com/opentargets/issues/issues/3170
**Deploy preview:** https://deploy-preview-326--ot-platform-partner.netlify.app/
=> [Platform]: Enhance upload functionality 

packages/sections/package.json, packages/sections/src/target/DepMap/DepmapPlot.jsx, yarn.lock
Using custom distributed packages from plotly instead of importing whole package.
**Issue:** # https://github.com/opentargets/issues/issues/3215
=> [Platform]: using custom distributed packages from plotly

apps/platform/public/robots.txt.production
#[Platform]: site maps disallow evidence pages from robots
=> [Platform]: site maps disallow evidence pages from robots

packages/sections/src/evidence/Chembl/Body.jsx, packages/sections/src/evidence/Chembl/ChemblQuery.gql, packages/sections/src/evidence/EVA/Body.jsx, packages/sections/src/evidence/EVA/ClinvarQuery.gql, packages/sections/src/evidence/EVASomatic/Body.jsx, packages/sections/src/evidence/EVASomatic/EvaSomaticQuery.gql, packages/sections/src/evidence/Gene2Phenotype/Body.jsx, packages/sections/src/evidence/GeneBurden/Body.jsx, packages/sections/src/evidence/GeneBurden/GeneBurdenQuery.gql, packages/sections/src/evidence/Impc/Body.jsx, packages/sections/src/evidence/Impc/sectionQuery.gql, packages/sections/src/evidence/OTGenetics/Body.jsx, packages/sections/src/evidence/OTGenetics/sectionQuery.gql, packages/sections/src/evidence/Orphanet/Body.jsx, packages/sections/src/evidence/Orphanet/OrphanetQuery.gql, packages/ui/src/components/DirectionOfEffectIcon.tsx, packages/ui/src/index.tsx
**Issue:** # https://github.com/opentargets/issues/issues/3207
=> [Platform]: direction of effect column

apps/platform/src/components/AssociationsToolkit/static_datasets/prioritisationColumns.ts, packages/sections/src/drug/Pharmacogenomics/Body.jsx, packages/sections/src/drug/Pharmacogenomics/Pharmacogenomics.gql, packages/sections/src/evidence/Chembl/Body.jsx, packages/sections/src/target/Pharmacogenomics/Pharmacogenomics.gql, packages/sections/src/target/Pharmacogenomics/PharmacogenomicsTable.jsx
Adding a new column containing link. If link id is null it will show without link, if show id is null it will display link id with link id text.
**Issue:** # https://github.com/opentargets/issues/issues/3219
**Deploy preview:** https://deploy-preview-335--ot-platform.netlify.app/target/ENSG00000138109
=> [Platform]: pharmgkb allele column

packages/sections/package.json, yarn.lock
Library version of "protvista-uniprot" updated to its version.
**Issue:** # https://github.com/opentargets/issues/issues/3138
=> [Package]: protvista-uniprot version updated

packages/sections/src/evidence/Chembl/Body.jsx, packages/sections/src/evidence/EVA/Body.jsx, packages/sections/src/evidence/EVASomatic/Body.jsx, packages/sections/src/evidence/Gene2Phenotype/Body.jsx, packages/sections/src/evidence/GeneBurden/Body.jsx, packages/sections/src/evidence/Impc/Body.jsx, packages/sections/src/evidence/OTGenetics/Body.jsx, packages/sections/src/evidence/Orphanet/Body.jsx
DOE documentation link update
**Issue:** # https://github.com/opentargets/issues/issues/3207
=> [Platform]: DOE documentation link update

apps/platform/src/pages/DiseasePage/ClassicAssociations.jsx, apps/platform/src/pages/TargetPage/ClassicAssociations.jsx, packages/ui/src/components/NewChip.tsx
Add info text to users when access _classic associations_
=> [Platform]: Classic associations warning text

packages/ui/src/components/DirectionOfEffectIcon.tsx
label updated for null values in DOE
**Issue:** # 
=> [Platform]: DOE null label updated

apps/platform/src/pages/ProjectsPage/projects-data.json, packages/sections/src/common/KnownDrugs/Body.jsx
**Issue:** # https://github.com/opentargets/issues/issues/3281 https://github.com/opentargets/issues/issues/3284
=> [Platform]: Known Drugs `mechanismsOfAction` handle null

packages/sections/src/evidence/EVASomatic/Body.jsx
Fix clinvar somatic loading error, adding `fetchPolicy` to query resolves the issue
**Issue:** # https://github.com/opentargets/issues/issues/3291
=> [Platform]: fix clinvar somatic loading error

apps/platform/src/constants.js, packages/ui/src/constants.js
**Issue:** # https://github.com/opentargets/issues/issues/3306
=> [Platform]: partner footer update

packages/ui/src/components/LongList.tsx
Migrate the LongList component to TypeScript.
Closed state:
Open state:
=> [Package]: migrate LongList component to TypeScript

apps/genetics/src/components/ScrollToTop.tsx
Remove log from ScrollToTop component.
Application was built locally.
=> [Genetics]: remove log from ScrollToTop component

packages/ui/src/components/ExternalLink/CrisprDepmapLink.tsx
Migrate the CrisprDepmapLink component to TypeScript.
=> [Package]: migrate CrisprDepmapLink component to TypeScript

packages/ui/src/components/ExternalLink/ExternalLink.tsx
Migrate the ExternalLink component to TypeScript.
=> [Package]: migrate ExternalLink component to TypeScript

apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.jsx, apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociations.jsx
Moving AOTF upload feature to Open Targets Platform
**Issue:** # https://github.com/opentargets/issues/issues/3309
- Navigate to diseases associations
-  Navigate to target associations
=> [Platform]: AOTF uploads public

packages/ui/src/components/GlobalSearch/GlobalSearchLoadingState.tsx
Migrate the GlobalSearchLoadingState component to TypeScript.
=> [Package]: migrate GlobalSearchLoadingState component to TypeScript

packages/sections/src/target/Pharmacogenomics/Pharmacogenomics.gql, packages/sections/src/target/Pharmacogenomics/PharmacogenomicsTable.jsx
Handle drug combinations in pharmacogenetics
**Issue:** # https://github.com/opentargets/issues/issues/3205
**Deploy preview:** https://deploy-preview-384--ot-platform.netlify.app/target/ENSG00000001626
=> [Platform]: Handle drug combinations in pharmacogenetics

apps/platform/src/pages/ProjectsPage/projects-data.json
Update projects-data.json
**Issue:** # https://github.com/opentargets/issues/issues/3338
=> [Platform]: Update projects-data.json

apps/platform/src/components/AssociationsToolkit/DataUploader/DataUploader.jsx, packages/sections/src/evidence/Chembl/Body.jsx
Aotf public upload documentation link
**Issue:** # https://github.com/opentargets/issues/issues/3309
=> [Platform]: Aotf public upload documentation link

packages/sections/src/evidence/OTValidation/Body.jsx, packages/sections/src/evidence/OTValidation/OTValidationQuery.gql
VL widget update with new fields
**Issue:** # https://github.com/opentargets/issues/issues/3340
**Deploy preview:** https://deploy-preview-397--ot-platform-partner.netlify.app/evidence/ENSG00000148737/EFO_1001951
=> [Platform]: VL widget update with new fields

apps/platform/src/pages/VariantPage/Profile.tsx, packages/sections/src/variant/EVA/Summary.tsx, packages/sections/src/variant/InSilicoPredictors/Summary.tsx, packages/sections/src/variant/UniProtVariants/Summary.tsx
* Remove subtext from summaries
* add missing suspense element to sections
Checked in dev.
- [] I have commented my code, particularly in hard-to-understand areas
=> [Platform] Clean up variant page sections and summaries

packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Description.tsx, packages/sections/src/variant/QTLCredibleSets/index.ts
Minor updates to QTL credible sets widget.
Checked in dev.
=> [Platform] Update variant page QTL credible sets widget

apps/platform/.env, apps/platform/src/pages/VariantPage/Header.tsx, apps/platform/src/pages/VariantPage/VariantPage.gql, apps/platform/src/pages/VariantPage/VariantPage.tsx, apps/platform/src/pages/VariantPage/types.ts, packages/ui/src/components/ExternalLink/XRefLinks.tsx
Use API for variant page header.
Checked on dev
=> [Platform] Use API for variant page header

apps/genetics/package.json, apps/platform/package.json, packages/sections/package.json, packages/ui/package.json, yarn.lock
Update apollo client version to v3.10.8
=> [AppConfig]: Update apollo-client version

packages/ui/src/components/DirectionOfEffectIcon.tsx
DoE icon logic update
- Test A
- Test B
=> [Platform]: DoE icon logic update

apps/platform/src/pages/HomePage/HomePage.jsx, apps/platform/src/pages/HomePage/PPHomePage.jsx, apps/platform/src/pages/HomePage/searchExamples.ts, apps/platform/src/utils/global.js, packages/ui/src/hooks/useListOption.js
Add variant suggestions to home pages.
=> [Platform]: Add variant suggestions to home pages

packages/sections/src/evidence/CancerBiomarkers/BiomarkersDrawer.jsx, packages/sections/src/evidence/CancerBiomarkers/CancerBiomarkersEvidence.gql
Change variant field in the cancer biomarker evidence 
**Issue:** https://github.com/opentargets/issues/issues/3392
**Deploy preview:** https://deploy-preview-440--ot-platform.netlify.app/
- Test A
- Test B
=> [Platform]: Change variant field in the cancer biomarker evidence 

packages/sections/src/evidence/GeneBurden/Description.jsx
New data source added to gene burden
**Issue:** https://github.com/opentargets/issues/issues/3424
-  New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Test A
- Test B
=> [Platform]: New data source added to gene burden

apps/platform/src/pages/DownloadsPage/DownloadsPage.jsx, apps/platform/src/pages/ProjectsPage/ProjectsPage.jsx
Data table updated with ot table
**Issue:** https://github.com/opentargets/issues/issues/3420
- Test A
- Test B
=> [Platform]: data table updated with ot table

packages/ui/src/components/ChipList.tsx
Migrate the ChipList component to TypeScript.
=> [Package]: migrate ChipList component to TypeScript

packages/ui/src/components/ScientificNotation.tsx
Migrate the ScientificNotation component to TypeScript.
=> [Package]: migrate ScientificNotation component to TypeScript

packages/sections/src/evidence/OTValidation/Body.jsx
string updated to list
**Issue:** https://github.com/opentargets/issues/issues/3375
- Test A
- Test B
=> [Platform]: VL schema update 

packages/sections/src/evidence/Chembl/Body.jsx, packages/sections/src/evidence/Chembl/ChemblQuery.gql
Reported phenotypes tooltip added to disease column
**Issue:** https://github.com/opentargets/issues/issues/3430
- Test A
- Test B
=> [Platform]: reported phenotypes tooltip added to disease column

packages/sections/src/evidence/OTValidation/Body.jsx, packages/sections/src/evidence/OTValidation/OTValidationQuery.gql
VL query term updated
**Issue:** https://github.com/opentargets/issues/issues/3375
- Test A
- Test B
=> [Platform]: VL query term updated

yarn.lock
=> [Platform]: update lock file

.github/workflows/ci-genetics.yml, .github/workflows/ci-platform.yml
=> [AppConfig]: update node version

packages/sections/src/target/DepMap/DepmapPlot.jsx
**Issue:** https://github.com/opentargets/issues/issues/3366#issuecomment-2340351902
**Deploy preview:** https://deploy-preview-471--ot-platform.netlify.app/
- Test A
- Test B
=> [Platform]: Depmap graph changes

apps/platform/src/pages/ProjectsPage/projects-data.json
Updated PPP projects-data.json to add OTAR 3092, 3093, 3094
**Issue:**
**Deploy preview:** 
- Test A
- Test B
=> [Platform]: updated PPP projects-data.json

apps/platform/src/components/AssociationsToolkit/components/RowInteractors/RowInteractorsTable.tsx, apps/platform/src/components/AssociationsToolkit/components/RowInteractors/useRowInteractors.js, apps/platform/src/components/AssociationsToolkit/components/Table/CellName.jsx, apps/platform/src/components/AssociationsToolkit/components/Table/SectionRender.jsx, apps/platform/src/components/AssociationsToolkit/components/Table/TableBody.jsx, apps/platform/src/components/AssociationsToolkit/components/layout.tsx, apps/platform/src/components/AssociationsToolkit/context/AssociationsFocusContext.tsx
Improvement based on feedback from AotF interactors
- PPP Interactors
=> [Platform]: AotF Target interactors UI recap

packages/ui/src/components/ClinvarStars.tsx
clinvar review status fix but removing extra variable and just comparing index(total star) to the number prop(active star).
**Issue:** https://github.com/opentargets/issues/issues/3550
- Test A
- Test B
=> [Platform]: clinvar review status fix

packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/QTLCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx, packages/sections/src/study/SharedTraitStudies/SharedTraitStudiesQuery.gql, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/Pharmacogenomics/PharmacogenomicsTable.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql
Minor updates to widgets on variant and study page.
=> [Platform] Minor updates to widgets on variant and study pages

apps/platform/src/pages/StudyPage/ProfileHeader.gql, apps/platform/src/pages/StudyPage/ProfileHeader.tsx, apps/platform/src/pages/VariantPage/ProfileHeader.tsx
Metadata updates for variant and study page.
**Issue:** [#3377](https://github.com/opentargets/issues/issues/3377)
=> [Platform]: Metadata updates for variant and study page

apps/platform/src/App.tsx, apps/platform/src/pages/CredibleSetPage/CredibleSetPage.gql, apps/platform/src/pages/CredibleSetPage/CredibleSetPage.tsx, apps/platform/src/pages/CredibleSetPage/Header.tsx, apps/platform/src/pages/CredibleSetPage/Profile.tsx, apps/platform/src/pages/CredibleSetPage/ProfileHeader.gql, apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx, apps/platform/src/pages/CredibleSetPage/index.ts, packages/ui/src/components/Summary/utils.js
Add credible set page - including header and metadata.
**Issue:** [#3436](https://github.com/opentargets/issues/issues/3436)
**Deploy preview:**  https://deploy-preview-492--ot-platform.netlify.app/credible-set/7557755549988633744
=> [Platform]: Add credible set page

packages/ui/src/components/DirectionOfEffectTooltip.tsx
Migrate the DirectionOfEffectTooltip component to TypeScript.
=> [Package]: migrate DirectionOfEffectTooltip component to TypeScript

packages/ui/src/components/BasePage.tsx
Migrate the BasePage component to TypeScript.
=> [Package]: migrate BasePage component to TypeScript

packages/ui/src/components/Page.tsx
Migrate the Page component to TypeScript.
=> [Package]: migrate Page component to TypeScript

packages/ui/src/components/ProfileHeader/Field.tsx
Migrate the Field component to TypeScript.
=> [Package]: migrate Field component to TypeScript

packages/ui/src/components/ProfileHeader/Description.tsx
Migrate the Description component to TypeScript.
=> [Package]: migrate Description component to TypeScript

apps/platform/src/App.tsx
[Platform] Disable PPP dialog on genetics branch.
**Issue:**
Checked on dev
=> [Platform] Disable PPP dialog on genetics branch

apps/platform/src/pages/CredibleSetPage/ProfileHeader.gql, apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx, apps/platform/src/pages/StudyPage/Header.tsx, apps/platform/src/pages/StudyPage/ProfileHeader.tsx, packages/sections/src/utils/getStudyCategory.ts
[Platform] Minor updates to credible sets and study pages.
**Issue:** [#3580](https://github.com/opentargets/issues/issues/3580)
=> [Platform] Minor updates to credible sets and study pages

packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/QTLCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx
=> [Platform]: fix study sections

packages/sections/src/drug/AdverseEvents/Body.jsx, packages/sections/src/drug/MechanismsOfAction/Body.jsx, packages/ui/src/components/OtTable/OtTable.tsx, packages/ui/src/components/OtTable/tableUtil.ts, packages/ui/src/components/Section/SectionItem.tsx
using useEffect hook to set data in a state for table instead of const.
**Deploy preview:** https://deploy-preview-520--ot-platform.netlify.app/
- Test A: switch to different id of same entity from given page(eg: drug to drug).
=> [Platform]: fix data prop in table

packages/ui/src/components/OtTable/OtTable.tsx, packages/ui/src/components/Section/SectionItem.tsx
- Check entity pages
-  [x] I have made corresponding changes to the documentation
=> [Platform]: fix section/table crash

packages/sections/src/variant/VariantEffectPredictor/Description.tsx, packages/sections/src/variant/VariantEffectPredictor/index.ts
Renamed VEP widget, enhanced description and link name.
=> refactor: rename VEP widget

.travis.yml
PR Tittle Format: [Genetics || Platform || PackageName || AppConfig]: Short description mentioning the affected page and/or section component
- Test A
- Test B
=> [Platform]: fix: travis deploy

apps/platform/src/pages/EvidencePage/Profile.jsx, packages/sections/src/evidence/GWASCredibleSets/Body.jsx, packages/sections/src/evidence/GWASCredibleSets/sectionQuery.gql
new Genetics evidence widget
**Issue:** https://github.com/opentargets/issues/issues/3604
- Test A
- Test B
=> [Platform]: new Genetics evidence widget

packages/ui/src/components/OtTable/OtTableColumnVisibility.tsx, packages/ui/src/components/OtTable/otTableLayout.tsx, packages/ui/src/components/OtTable/tableUtil.ts
Nested columns, 2  level header support added
- Test A
- Test B
=> [Platform]: nested columns

apps/platform/src/pages/VariantPage/ProfileHeader.tsx, apps/platform/src/pages/VariantPage/ProfileHeaderLoader.tsx, packages/sections/src/variant/VariantEffectPredictor/Body.tsx, packages/ui/src/components/OtTable/OtTable.tsx, packages/ui/src/components/OtTable/table.types.ts, packages/ui/src/components/Section/SectionItem.tsx
table/section fix
**Deploy preview:** https://deploy-preview-525--ot-platform.netlify.app/
- Test A
- Test B
=> [Platform]: table/section fix

apps/platform/src/pages/EvidencePage/Profile.jsx, packages/sections/src/evidence/GWASCredibleSets/Body.jsx, packages/sections/src/evidence/GWASCredibleSets/GWASCredibleSetsSummary.gql, packages/sections/src/evidence/GWASCredibleSets/Summary.jsx, packages/sections/src/evidence/GWASCredibleSets/index.js, packages/sections/src/evidence/GWASCredibleSets/sectionQuery.gql, packages/sections/src/variant/GWASCredibleSets/Body.tsx
gwas cred columns
**Issue:** https://github.com/opentargets/issues/issues/3604
- Test A
- Test B
=> [Platform]: gwas cred columns

packages/ui/src/components/ClinvarStars.tsx
Different colours in ClinVar stars
**Issue:** https://github.com/opentargets/issues/issues/3583
- Test A
- Test B
=> [Platform]: Different colours in ClinVar stars

packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsQuery.gql, packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsSummaryFragment.gql, packages/sections/src/variant/GWASCredibleSets/index.ts, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql, packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql, packages/sections/src/variant/QTLCredibleSets/index.ts
=> [Platform]: variant page queries update

apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx, apps/platform/src/pages/StudyPage/ProfileHeader.tsx, packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/GWASColoc/Description.tsx, packages/sections/src/credibleSet/GWASMolQTL/Body.tsx, packages/sections/src/credibleSet/GWASMolQTL/Description.tsx, packages/sections/src/credibleSet/Locus2Gene/Description.tsx, packages/sections/src/credibleSet/Variants/Body.tsx, packages/sections/src/credibleSet/Variants/Description.tsx, packages/sections/src/credibleSet/Variants/index.ts, packages/sections/src/disease/GWASStudies/Body.tsx, packages/sections/src/evidence/EVA/Body.jsx, packages/sections/src/evidence/EVASomatic/Body.jsx, packages/sections/src/evidence/GWASCredibleSets/Body.jsx, packages/sections/src/evidence/GWASCredibleSets/Description.jsx, packages/sections/src/evidence/OTGenetics/Body.jsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/GWASCredibleSets/Description.tsx, packages/sections/src/study/GWASCredibleSets/ManhattanPlot.tsx, packages/sections/src/study/QTLCredibleSets/Body.tsx, packages/sections/src/study/QTLCredibleSets/Description.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Description.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Description.tsx, packages/sections/src/variant/VariantEffectPredictor/Body.tsx
Each commit in this PR contains a change in labels to add consistency or improve the interpretation
Work in progress
=> refactor: changes in labels

apps/platform/src/pages/StudyPage/Profile.tsx
Flipping the 2 widgets in study page
=> refactor: reorder study page widgets

packages/sections/src/evidence/GWASCredibleSets/Body.jsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx
Tooltip added to same column in 3 widgets
=> feat: finemapping confidence tooltip

packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/ui/src/components/Section/SectionViewToggle.tsx
=> [Platform]: styles vis controls

apps/platform/src/pages/HomePage/HomePage.jsx, packages/ui/src/components/Section/sectionStyles.js, packages/ui/src/components/Summary/summaryStyles.js
=> [Platform]: fix home suggestion links

packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx
=> [Platform]: fix locus validation on Variant widgets

apps/platform/src/constants.js, apps/platform/src/pages/CredibleSetPage/ProfileHeader.gql, apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx, packages/sections/package.json, packages/ui/package.json, packages/ui/src/components/LabelChip.tsx
- Population chips added + dictionary for tooltip
- Quiet linters
- Confidence stars moved + tooltip
=> [Platform]: population structure, confidence refactor, quiet lints

packages/sections/src/credibleSet/Variants/Body.tsx
logBF column changes:
- edited name
- sorting allowed
- tooltip added
=> [Platform]: logbf column explanation

packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsQuery.gql, packages/ui/src/hooks/useBatchQuery.ts
Use batching in GWAS credible set widget on study page.
Checked on study page (e.g. `study/GCST90239652`)
=> [Platform]: Use batching in GWAS credible set widget on study page

apps/platform/src/pages/VariantPage/ProfileHeader.tsx
Correct label in allele frequency chart
Checked variant page
=> [Platform]: Correct label in allele frequency chart

packages/sections/src/variant/Pharmacogenomics/Body.tsx
Fix phenotype label in PGx widget
Issue: [#3636](https://github.com/opentargets/issues/issues/3636)
Checked on variant page.
=> [Platform]: Fix phenotype label in PGx widget

packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsQuery.gql, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql
=> [Platform]: fix variant study schema

apps/platform/src/pages/CredibleSetPage/ProfileHeader.gql, apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx
- Summary statistics availabilitty + sumstats qc to study section in credible set page
- Analysis type to study section in credible set page
=> [Platform]: feat add summary statistics and analysis flag to study in credible set page

apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx, packages/sections/src/study/GWASCredibleSets/index.ts, packages/sections/src/study/SharedTraitStudies/Body.tsx
=> [Platform]: fix Credible set profile bug

apps/platform/src/components/Search/SearchQuery.gql, apps/platform/src/pages/SearchPage/SearchPageQuery.gql, apps/platform/src/pages/SearchPage/VariantDetail.jsx, apps/platform/src/pages/SearchPage/VariantResult.jsx, apps/platform/src/pages/VariantPage/ProfileHeader.gql, apps/platform/src/pages/VariantPage/ProfileHeader.tsx, packages/ui/src/components/GlobalSearch/GlobalSearchListItem.jsx
Add variant description to search results and variant page metadata
**Issue:** [#3644](https://github.com/opentargets/issues/issues/3644)
Checked on search and variant page
=> [Platform] Add variant description to search results and variant page metadata

apps/platform/src/pages/HomePage/HomePage.jsx, packages/sections/src/target/MolecularInteractions/IntactTab.jsx, packages/sections/src/target/MolecularInteractions/ReactomeTab.jsx, packages/sections/src/target/MolecularInteractions/SignorTab.jsx, packages/sections/src/target/MolecularInteractions/StringTab.jsx
=> [Platform]: fix target molecular interactors 

packages/sections/src/evidence/GWASCredibleSets/Body.jsx, packages/sections/src/evidence/GWASCredibleSets/Summary.jsx, packages/ui/src/components/PublicationsDrawer/PublicationWrapper.jsx
Fix the evidence page and publication across UI.
**Issue:** https://github.com/opentargets/issues/issues/3661 
- Check evidence page
- Check GWAS evidence widget
- Check Study page publication columns
=> [Platform]: fix the evidence page and publication across UI

packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsQuery.gql
PR Tittle Format: [Genetics || Platform || PackageName || AppConfig]: Short description mentioning the affected page and/or section component
- Test A
- Test B
=> [Platform]: `l2GPredictions`schema change 

packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsQuery.gql
=> [Platform]: fix gwas widget in study

apps/platform/src/pages/StudyPage/Profile.tsx, apps/platform/src/pages/StudyPage/StudyProfileHeader.gql, apps/platform/src/pages/StudyPage/StudyProfileHeader.tsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx, packages/sections/src/study/SharedTraitStudies/SharedTraitStudiesQuery.gql, packages/sections/src/study/SharedTraitStudies/index.ts
Study page fixes:
- use batching in shared trait studies widget
- remove page study from shared trait studies widget results
- show loading message in GWAS cedible sets widget (is already batching)
- add condition column to metadata
Checked study page.
=> [Platform]: Study page fixes

packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/MolQTLColoc/Body.tsx, packages/sections/src/credibleSet/Variants/Body.tsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/QTLCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/ui/src/components/ScientificNotation.tsx
Numeric formatting in table columns on genetic pages.
**Issue:** [#3666](https://github.com/opentargets/issues/issues/3666)
Checked relevant changes.
=> [Platform] Numeric formatting on new pages

packages/sections/src/variant/InSilicoPredictors/Body.tsx, packages/sections/src/variant/InSilicoPredictors/InSilicoPredictorsPlot.tsx, packages/sections/src/variant/InSilicoPredictors/InSilicoPredictorsQuery.gql, packages/ui/src/components/Section/SectionItem.tsx, packages/ui/src/components/Section/SectionViewToggle.tsx, packages/ui/src/constants.js, yarn.lock
**Issue:** https://github.com/opentargets/issues/issues/3628
**Deploy preview:** https://deploy-preview-594--ot-platform-partner.netlify.app/
- Check variant page
=> [Platform]: Insilico predictors chart

packages/sections/src/credibleSet/MolQTLColoc/Body.tsx, packages/sections/src/credibleSet/MolQTLColoc/MolQTLColocQuery.gql
Update molQTL coloc columns on credible set page.
Checked credible set page.
=> [Platform]: Update molQTL coloc columns on credible set page

packages/sections/src/variant/InSilicoPredictors/Body.tsx, packages/sections/src/variant/InSilicoPredictors/InSilicoPredictorsPlot.tsx
This pull request includes several changes to the `InSilicoPredictors` components to improve code quality and functionality.
=> [Platform]: enhance InSilicoPredictors component 

apps/platform/src/pages/StudyPage/Header.tsx, packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/Locus2Gene/Body.tsx, packages/sections/src/evidence/GWASCredibleSets/Body.jsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsQuery.gql, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/VariantEffectPredictor/Body.tsx
Closes https://github.com/opentargets/issues/issues/3668
and 2 additional issues:
- a topL2GPredictions query was wrongly specified as [index:1, size:1]. It was returning second top L2G
- I renamed UKB to UKB-PPP (already discussed)
=> [Platform]: fix several issues in exports

apps/platform/src/pages/StudyPage/StudyProfileHeader.tsx
Use drawer instead of hardcoded link
=> [Platform]: publication drawer in study page

packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/GWASCredibleSets/PheWasPlot.tsx
=> [Platform]: Phewas chart add export data and query playground

packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/Variants/Body.tsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx
=> [Platform]: Fix sections gql playground

packages/sections/src/disease/GWASStudies/Body.tsx
Fix gql playground for studies widget on disease page.
Checked on disease page.
=> [Playground]: Fix gql playground for studies widget on disease page

packages/ui/src/components/SummaryStatsTable.tsx
Format values in summary stats popover.
Checked on study. and credible sets pages
=> [Platform]: Format values in summary stats popover

packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/MolQTLColoc/Body.tsx, packages/sections/src/credibleSet/Variants/Body.tsx, packages/sections/src/disease/GWASStudies/Body.tsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx
**Issue:** [#3670](https://github.com/opentargets/issues/issues/3670)
Checked fixes bug in ticket and that batching still works as expected.
=> [Platform]: Use dependency in batching to force widget rerender

apps/platform/src/pages/VariantPage/ProfileHeader.tsx
Add source to allele frequency plot
Checked on variant page.
=> [Platform]: Add source to allele frequency plot

packages/sections/src/credibleSet/MolQTLColoc/index.ts
Fix GWAS credible set summary link in credible set page.
Also change short name for molQTL colloc.
Checked on credible set page.
=> [Platform]: Fix GWAS credible set summary link in credible set page

packages/sections/src/target/MolecularInteractions/StringTab.jsx, packages/ui/src/components/PublicationsDrawer/PublicationsDrawer.jsx
=> [Platform]: Pending client table

apps/platform/src/theme.ts, packages/sections/src/evidence/CRISPR/Body.jsx, packages/sections/src/evidence/CRISPRScreen/Body.jsx, packages/sections/src/evidence/CancerBiomarkers/Body.jsx, packages/sections/src/evidence/CancerGeneCensus/Body.jsx, packages/sections/src/evidence/Chembl/Body.jsx, packages/sections/src/evidence/ClinGen/Body.jsx, packages/sections/src/evidence/EVA/Body.jsx, packages/sections/src/evidence/EVASomatic/Body.jsx, packages/sections/src/evidence/EuropePmc/Body.jsx, packages/sections/src/evidence/ExpressionAtlas/Body.jsx, packages/sections/src/evidence/GWASCredibleSets/Body.jsx, packages/sections/src/evidence/Gene2Phenotype/Body.jsx, packages/sections/src/evidence/GeneBurden/Body.jsx, packages/sections/src/evidence/GenomicsEngland/Body.jsx, packages/sections/src/evidence/Impc/Body.jsx, packages/sections/src/evidence/IntOgen/Body.jsx, packages/sections/src/evidence/OTCRISPR/Body.jsx, packages/sections/src/evidence/OTEncore/Body.jsx, packages/sections/src/evidence/OTValidation/Body.jsx, packages/sections/src/evidence/Orphanet/Body.jsx, packages/sections/src/evidence/Progeny/Body.jsx, packages/sections/src/evidence/Reactome/Body.jsx, packages/sections/src/evidence/SlapEnrich/Body.jsx, packages/sections/src/evidence/SysBio/Body.jsx, packages/sections/src/evidence/UniProtLiterature/Body.jsx, packages/sections/src/evidence/UniProtVariants/Body.jsx, packages/ui/src/components/OtAsyncTooltip/OtAsyncTooltip.tsx
Active async tooltip on evidence widgets
**Issue:** https://github.com/opentargets/issues/issues/3763
=> [Platform]: Async tooltip evidence

packages/sections/src/variant/EVA/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/Pharmacogenomics/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/UniProtVariants/Body.tsx, packages/sections/src/variant/VariantEffectPredictor/Body.tsx
=> [Platform]: Async tooltip variant

packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/Locus2Gene/Body.tsx, packages/sections/src/credibleSet/MolQTLColoc/Body.tsx, packages/sections/src/credibleSet/Variants/Body.tsx
=> [Platform]: Async tooltip credible-set

packages/sections/src/drug/DrugWarnings/Body.jsx, packages/sections/src/drug/Indications/Body.jsx, packages/sections/src/drug/KnownDrugs/Body.jsx, packages/sections/src/drug/Pharmacogenomics/Body.jsx
=> [Platform]: Async tooltip drug 

packages/sections/src/disease/GWASStudies/Body.tsx, packages/sections/src/disease/KnownDrugs/Body.jsx, packages/sections/src/disease/Phenotypes/Body.jsx
=> [Platform]: Async tooltip disease

packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/QTLCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx
=> [Platform]: Async tooltip study

apps/platform/src/components/AssociationsToolkit/static_datasets/dataSourcesAssoc.js
[Platform]: remove old ot genetics from aotf
PR Tittle Format: [Genetics || Platform || PackageName || AppConfig]: Short description mentioning the affected page and/or section component
- Test A
- Test B
=> [Platform]: remove old ot genetics from aotf

packages/sections/src/study/SharedTraitStudies/Body.tsx
add entity to relative link
- Test A
- Test B
=> [Platform]: add entity to relative link

packages/sections/src/target/ComparativeGenomics/Body.jsx, packages/sections/src/target/ComparativeGenomics/ChimpanzeeIcon.tsx, packages/sections/src/target/ComparativeGenomics/ComparativeGenomicsPlot.tsx, packages/sections/src/target/ComparativeGenomics/Description.tsx, packages/sections/src/target/ComparativeGenomics/DogIcon.tsx, packages/sections/src/target/ComparativeGenomics/FlyIcon.tsx, packages/sections/src/target/ComparativeGenomics/FrogIcon.tsx, packages/sections/src/target/ComparativeGenomics/GuineaPigIcon.tsx, packages/sections/src/target/ComparativeGenomics/HumanIcon.tsx, packages/sections/src/target/ComparativeGenomics/MacaqueIcon.tsx, packages/sections/src/target/ComparativeGenomics/MouseIcon.tsx, packages/sections/src/target/ComparativeGenomics/PigIcon.tsx, packages/sections/src/target/ComparativeGenomics/RabbitIcon.tsx, packages/sections/src/target/ComparativeGenomics/RatIcon.tsx, packages/sections/src/target/ComparativeGenomics/Visualisation.jsx, packages/sections/src/target/ComparativeGenomics/WormIcon.tsx, packages/sections/src/target/ComparativeGenomics/ZebrafishIcon.tsx
Issue: https://github.com/opentargets/issues/issues/3768
Fix the comparative genomics widget
=> [Platform]: fix comparative genomics

apps/platform/src/pages/APIPage/APIPage.jsx, apps/platform/src/pages/APIPage/CredibleSetAnnotation.gql, apps/platform/src/pages/APIPage/DiseaseAnnotationGWAS.gql, apps/platform/src/pages/APIPage/SearchAnnotation.gql, apps/platform/src/pages/APIPage/SearchAssocs.gql, apps/platform/src/pages/APIPage/StudyAnnotation.gql, apps/platform/src/pages/APIPage/VariantAnnotation.gql
Added new example queries
**Issue:** https://github.com/opentargets/issues/issues/3722
**Deploy preview:** https://deploy-preview-652--ot-platform-partner.netlify.app/api
- Test A
- Test B
=> [Platform]: Added new example queries

apps/platform/src/pages/APIPage/APIPage.jsx, apps/platform/src/pages/APIPage/SearchAnnotation.gql
Added new example queries
**Issue:** https://github.com/opentargets/issues/issues/3722
**Deploy preview:** 
- Test A
- Test B
=> [Platform]: Added new search example queries

packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/MolQTLColoc/Body.tsx
Fix coloc credible sets links on credible set page
=> [Platform]: Fix coloc credible sets links on credible set page

apps/platform/src/pages/SearchPage/StudyResult.jsx
Study meta data function used in search results page
**Issue:** https://github.com/opentargets/issues/issues/3561#issuecomment-2663494941
- Test A
- Test B
=> [Platform]: Study meta data function used in search results page

packages/ui/src/components/GlobalSearch/GlobalSearchDialog.jsx, packages/ui/src/components/GlobalSearch/GlobalSearchFreeListItem.jsx, packages/ui/src/components/GlobalSearch/GlobalSearchList.jsx, packages/ui/src/components/GlobalSearch/GlobalSearchListItem.jsx, packages/ui/src/components/GlobalSearch/VariantMessage.tsx
Add variant id match patterns to validate if the user input is possible a variant id 
**Issue:** https://github.com/opentargets/issues/issues/3627
=> [Platform]: Variant not available in search results message

packages/ui/src/components/OtAsyncTooltip/OtAsyncTooltip.tsx
- Added null check for empty array and return default string
**Issue:** https://github.com/opentargets/issues/issues/3763
- Test A
- Test B
=> [Platfomr]: no description crash

apps/platform/src/pages/SearchPage/SearchContainer.jsx, apps/platform/src/pages/SearchPage/SearchPage.jsx
Empty search results page added instead of 404 message.
**Issue:** https://github.com/opentargets/issues/issues/3777
**Deploy preview:** https://deploy-preview-663--ot-platform-partner.netlify.app/
- Navigate to the search page
- Enter a search term that will return no results (e.g., "xyz123nonexistent")
- Submit the search
- Observe new search results page.
=> [Platform]: Empty search results page 

apps/platform/src/pages/CredibleSetPage/Profile.tsx, apps/platform/src/pages/CredibleSetPage/ProfileHeader.gql, packages/sections/src/credibleSet/GWASColoc/GWASColocSummaryFragment.gql, packages/sections/src/credibleSet/Locus2Gene/Locus2GeneQueryFragment.gql, packages/sections/src/credibleSet/MolQTLColoc/MolQTLColocSummaryFragment.gql, packages/sections/src/credibleSet/Variants/VariantsSummaryFragment.gql
=> [Platform]: Fix credible set profile

packages/ui/src/components/GlobalSearch/VariantMessage.tsx
=> [Platform]: adjust variant search message

apps/platform/vite.config.js, packages/ot-config/src/environment.ts, packages/ot-config/src/index.ts, packages/ot-config/src/types.ts, packages/ui/src/components/Footer.tsx
=> [Platform]: add git version to UI

packages/ui/src/components/OtTable/OtTable.tsx, packages/ui/src/components/OtTable/OtTableSSP.tsx, packages/ui/src/components/OtTable/otTableLayout.tsx, packages/ui/src/components/OtTable/types/tableTypes.ts
=> [Platform]: selecting rows in the table

apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx, apps/platform/src/pages/StudyPage/StudyProfileHeader.tsx, packages/ot-utils/src/global.ts
**Issue:** https://github.com/opentargets/issues/issues/3795
- Test A
- Test B
=> [Platform]: sorting ancestries in credible set page

apps/platform/src/components/AssociationsToolkit/components/ActiveFiltersPanel.tsx
=> [Platform]: fix filters in resetAll

packages/sections/src/evidence/GeneBurden/Description.jsx
Closes https://github.com/opentargets/issues/issues/3798
=> [Platform]: generalise link to documentation for burden test

packages/ui/src/components/Section/SectionItem.tsx
=> [Platform]: section item avoid re-renders

packages/sections/src/evidence/GeneBurden/Body.jsx
I have updated the list of links for gene burden projects that show the burden results in a portal.
None
=> chore(platform): update references list for burden projects

packages/ui/src/components/HeatmapTable/HeatmapLegend.tsx
More concise wording for the legend
=> feat: slightly change in wording

apps/platform/src/pages/SearchPage/DrugResult.jsx
Fix drug url on search results page
Checked on dev
=> [Platform]: Fix drug url on search results page

apps/platform/src/components/AssociationsToolkit/components/ActiveFiltersPanel.tsx, apps/platform/src/components/AssociationsToolkit/components/Table/CellName.jsx, apps/platform/src/components/AssociationsToolkit/components/Table/TableAssociations.jsx, apps/platform/src/components/AssociationsToolkit/context/AssociationsFocusContext.tsx, apps/platform/src/components/AssociationsToolkit/context/AssociationsStateContext.jsx, apps/platform/src/components/Facets/FacetsSearch.tsx, packages/sections/src/variant/UniProtVariants/Description.tsx
=> [Platform]: AotF filters bug fixes

apps/platform/src/pages/TargetPage/ProfileHeader.jsx
genome location styles
**Issue:** https://github.com/opentargets/issues/issues/3671#issuecomment-2715185598
- Test A
- Test B
=> [Platform]: genome location styles

packages/sections/src/evidence/GWASCredibleSets/Description.jsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/UniProtVariants/Body.tsx, packages/sections/src/variant/UniProtVariants/Description.tsx, packages/ui/src/components/HeatmapTable/HeatmapTable.tsx
=> [Platform]: L2g widget show all

packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql
is trans flag in mol qtl widget
**Issue:** https://github.com/opentargets/issues/issues/3752
- Test A
- Test B
=> [Platform]: is trans flag in mol qtl widget

package.json
=> [AppConfig]: set correct data version

apps/platform/src/pages/HomePage/HomePage.tsx, packages/ui/src/components/Footer.tsx, packages/ui/src/components/OtTable/OtTable.tsx, packages/ui/src/components/OtTable/OtTableSSP.tsx
accessibility fixes
- Test A
- Test B
=> [Platform]: accessibility fixes

apps/platform/src/components/AssociationsToolkit/static_datasets/dataSourcesAssoc.js, packages/sections/src/credibleSet/GWASColoc/Description.tsx, packages/sections/src/credibleSet/Locus2Gene/Description.tsx, packages/sections/src/credibleSet/MolQTLColoc/Description.tsx, packages/sections/src/credibleSet/Variants/Description.tsx, packages/sections/src/evidence/GWASCredibleSets/Description.jsx, packages/sections/src/study/GWASCredibleSets/Description.tsx, packages/sections/src/variant/GWASCredibleSets/Description.tsx, packages/sections/src/variant/QTLCredibleSets/Description.tsx, packages/sections/src/variant/VariantEffect/Description.tsx
[Platform]: Updated with new genetics docs for evidence and variant/study/credible widgets.
**Issue:**
- Check all documentation links are correct.
=> [Platform]: Updated with new genetics docs

apps/platform/src/pages/DownloadsPage/DownloadsPage.jsx
schema change for single source coming as object instead of array
- Test A
- Test B
=> [Platform]: schema change for single source

apps/platform/src/components/AssociationsToolkit/components/DataDownloader.jsx, apps/platform/src/pages/DownloadsPage/DownloadsPage.jsx
=> [Platform]: aotf and downloads bugs

apps/platform/src/pages/ProjectsPage/projects-data.json
Updating PPP projects data json with a new project and reordering and marking a project as closed.
=> [PPP] Update PPP projects-data

package.json
=> [Platform]: update data release version

apps/platform/etc/platform.conf, package.json
=> [Platform]: update ngnx config

packages/ot-constants/src/index.ts, packages/ot-constants/src/variant.ts, packages/sections/src/variant/VariantEffect/VariantEffectPlot.tsx
=> [Platform]: add dictionary for VEP

apps/platform/src/pages/DownloadsPage/DownloadsPage.jsx
Info text added on downloads page for PPP users.
**Deploy preview:** https://deploy-preview-722--ot-platform-partner.netlify.app/downloads
- Test A
- Test B
=> [Platform]: PPP info text on downloads page

packages/sections/src/target/ProtVista/Body.jsx
Adding a capture button for downloading canvas image
**Issue:** https://github.com/opentargets/issues/issues/3827
- Test A
- Test B
=> [Platform]: adding a capture button for downloading canvas image

packages/sections/src/evidence/Gene2Phenotype/Body.jsx
Correcting links in Gene2Phenotype
**Issue:** https://github.com/opentargets/issues/issues/3831
- Test A
- Test B
=> [Platform]: Correcting links in Gene2Phenotype

packages/sections/src/target/ProtVista/Body.jsx
handling empty container
**Issue:** https://github.com/opentargets/issues/issues/3830
- Test A
- Test B
=> [Platform]: Handling empty container

packages/sections/src/credibleSet/GWASColoc/Body.tsx, packages/sections/src/credibleSet/MolQTLColoc/Body.tsx, packages/sections/src/credibleSet/Variants/Body.tsx, packages/sections/src/disease/GWASStudies/Body.tsx, packages/sections/src/study/GWASCredibleSets/Body.tsx, packages/sections/src/study/SharedTraitStudies/Body.tsx, packages/sections/src/variant/GWASCredibleSets/Body.tsx, packages/sections/src/variant/QTLCredibleSets/Body.tsx, packages/ui/src/hooks/useBatchQuery.ts
Refactor `useBatchQuery` hook to prevent non renders
=> [Platform]: refactor `useBatchQuery` hook

apps/platform/src/pages/DownloadsPage/DownloadsCard.tsx
downloads null category fix
**Issue:** https://deploy-preview-739--ot-platform.netlify.app/
- Test A
- Test B
=> [Platform]: downloads null category fix

packages/ot-constants/src/index.ts
Updating EBI privacy notice
**Issue:** [3903](https://github.com/opentargets/issues/issues/3903)
=> [Platform]: Updating EBI privacy notice

package.json
=> [Platform]: Update data version `25.06`

packages/ui/src/components/GlobalSearch/GlobalSearchEntityFilter.tsx, packages/ui/src/components/GlobalSearch/GlobalSearchIcon.tsx, packages/ui/src/components/GlobalSearch/utils/searchUtils.js
adding all option in search category filter
**Deploy preview:** https://deploy-preview-747--ot-platform.netlify.app/
- Test A
- Test B
=> [Platform]: adding all option in search category filter

apps/platform/src/pages/DrugPage/DrugPage.gql, apps/platform/src/pages/DrugPage/Header.jsx
drug schema update
**Issue:** https://github.com/opentargets/issues/issues/3912
- Test A: go to drug page to see the headers and name should be working
=> [Platform]: drug schema update

apps/platform/src/pages/VariantPage/ProfileHeader.tsx, packages/ot-constants/src/variant.ts, packages/sections/src/variant/VariantEffect/Body.tsx, packages/sections/src/variant/VariantEffect/Description.tsx, packages/sections/src/variant/VariantEffect/VariantEffectPlot.tsx
mentions to Ensembl VEP in the Platform
**Issue:** https://github.com/opentargets/issues/issues/3829
- Test A
- Test B
=> [Platform]: mentions to Ensembl VEP in the Platform

apps/platform/src/pages/DownloadsPage/DownloadsAccessOptions.tsx, apps/platform/src/pages/ProjectsPage/ProjectsPage.jsx, apps/platform/src/pages/ProjectsPage/projects-data.json, packages/ui/src/components/OtTable/OtTableSSP.tsx
- entity redirection bug fix
- downloads access option link fix
- projects table label updated 
**Issue:** https://github.com/opentargets/issues/issues/3918 https://github.com/opentargets/issues/issues/3897
**Deploy preview:** https://deploy-preview-763--ot-platform.netlify.app/
- Test A
- Test B
=> [Platform]: entity redirection

apps/platform/src/pages/DownloadsPage/DownloadsAccessOptions.tsx
Downloads access links corrected:
- added ftp link to wget
- added content url to rsync
**Deploy preview:** https://deploy-preview-765--ot-platform.netlify.app/downloads
- Test A
- Test B
=> [Platform]: Downloads access links corrected

packages/sections/src/drug/MechanismsOfAction/Description.jsx
Adding empty array to null object
**Issue:** https://github.com/opentargets/issues/issues/3922
**Deploy preview:** https://deploy-preview-774--ot-platform.netlify.app/
- Test A
- Test B
=> [Platform]: fix null type

packages/sections/src/evidence/ClinGen/Body.jsx
download files name corrected
**Issue:** https://github.com/opentargets/issues/issues/3920
- Test A
- Test B
=> [Platform]: download files name corrected

packages/sections/src/disease/Phenotypes/Body.jsx
Closes https://github.com/opentargets/issues/issues/4014
=> fix: incomplete dictionary

apps/platform/.env
=> [Platform]: fix api url

packages/sections/src/variant/Intervals/Body.tsx, packages/sections/src/variant/Intervals/IntervalsQuery.gql
**Issue:** https://github.com/opentargets/issues/issues/4054
=> [Platform]: fix intervals table query 

apps/platform/etc/platform.conf
This PR adds a health check endpoint to the platform's nginx configuration.
=> [AppConfig] add healthcheck

apps/platform/src/pages/DownloadsPage/context/downloadsReducer.ts, apps/platform/src/pages/DownloadsPage/utils.js
**Issue:** https://github.com/opentargets/issues/issues/4094
=> [Platform]: fix downloads page data parser
