- apps/platform/src/pages/HomePage/ppSearchExamples.js
I have added a few more targets that are found in both the ot_crispr and validation lab datasets. 
I think we can keep the drugs as they are, as (as much as I am aware), none of the projects are focusing on any specific drugs.
> Adding new targets to the search suggestion lists.

- apps/platform/src/sections/target/SubcellularLocation/SubcellularViz.jsx
This PR addresses a re-rendering of the target page when the subcellular location viz is loaded as noted here https://github.com/opentargets/issues/issues/2654
This appeared to be caused by a missing <Suspense> element to wrap the lazy-loaded visualisation.
> Fix subcellular location triggering re-rendering of target page

- apps/genetics/src/components/Header/OTButtonLink.jsx
- apps/genetics/src/config.js
When providing a value for `platformUrl` that contains a trailing slash, the corresponding links on the gene page will not work due to double slashes. This change removes the trailing slash from `platformUrl` if one exists.
> More robust handling of `platformUrl`

- apps/platform/src/components/PartnerLockIcon.jsx
- apps/platform/src/pages/EmptyPage/EmptyPage.jsx
Unless there is a reason to keep hard-coded email addresses in some places, I suggest using the email address from the config file everywhere.
Same PR as https://github.com/opentargets/platform-app/pull/551 in old frontend repo.
> Replace hard-coded email addresses with `helpdeskEmail from config

- apps/genetics/src/components/ForestPlot.jsx
- apps/genetics/src/components/PheWASSection.jsx
- apps/genetics/src/ot-ui-components/components/ListTooltip.jsx
This PR improves the user experience of the forest-plot as suggested in: https://github.com/opentargets/issues/issues/2667#issuecomment-1184262363
- added a subtitle to forest plot
- matched chip colors with chip colors of PheWAS chart
- made table with trait names and p-values stick to the left side of the screen to prevent loss of context on horizontal scrolling
- fixed X-Axis overlap
> Rm forestplot

- apps/platform/index.html
When scrolling passed the top or bottom of the page, a blue background is shown. This is good, but not desirable on PPP. https://github.com/opentargets/issues/issues/2589
After investigating a few options, I suggest simply **setting the background to** standard **white**:
- simple solution that looks **consistent across browsers**
- using theme colour (which would be different for PPP) is more fiddly and
- theme colour would only work at the top of the page, as the footer is dark grey
> Fix body background color on scroll bounce

- apps/platform/src/sections/target/ChemicalProbes/ChemicalProbes.gql
This will become necessary with the next API release.
Relates to opentargets/issues#2730
> Update `probesDrugScore` to `probesDrugsScore`

- apps/genetics/src/sections/studyLocus/ColocL2GTable/ColocL2GTable.jsx
The `getData()` function will return `false` if length of provided array is 0, which in this case will be used to overwrite the empty array that is used as a default value for `tableData`.
See the following example: https://genetics.opentargets.org/study-locus/GCST009337/18_29921527_G_A
> Fix breaking `ColocL2GTable` when no data is available

- apps/platform/src/sections/evidence/Gene2Phenotype/Body.jsx
- apps/platform/src/sections/evidence/Gene2Phenotype/sectionQuery.gql
Fix the empty literature column (showing as N/A) in the G2P widget, due to incorrect fields in query. Also refactor to use correct PublicationDrawer component. 
See [issue 2781](https://github.com/opentargets/issues/issues/2781)
> Fix emtpy literature column in Gene2Phenotype evidence widget

- apps/platform/src/sections/evidence/Gene2Phenotype/Body.jsx
- apps/platform/src/sections/evidence/Gene2Phenotype/sectionQuery.gql
- apps/platform/src/sections/evidence/Orphanet/Body.jsx
- apps/platform/src/sections/evidence/Orphanet/OrphanetQuery.gql
Add a "Functional consequence" column to Orphanet and Gene2Phenotype evidence widgets as per [this issue](https://github.com/opentargets/issues/issues/2640) 
Note: flagging as draft until G2P data is pending.
> Add functional consequence to Orphanet and Gene2Phenotype evidence

- apps/platform/src/components/Legend.jsx
- apps/platform/src/sections/target/MolecularInteractions/StringTab.jsx
Update the Legend component to support config props for the info link; fix incorrect Legend link in the String table (Molecular interactions widget). As per [issue 2747](https://github.com/opentargets/issues/issues/2747).
> Update Legend component for Molecular Interactions widget

- apps/platform/src/sections/evidence/GeneBurden/Body.jsx
Account for case where cohortId is `null` as per [issue 2805](https://github.com/opentargets/issues/issues/2805)
> Update logic for null cohortId

- apps/platform/src/pages/DiseasePage/ClassicAssociationsTable.jsx
- apps/platform/src/pages/TargetPage/ClassicAssociationsTable.jsx
Specify a datatypes' column label for download. This fixes issue [Associations heatmaps columns headers are incorrect in downloaded file](https://github.com/opentargets/issues/issues/2814)
For private PPP fields we also append `Private` at the end (essentially in place of the lock icon), e.g. `otarProjectsPrivate` - @buniello do let me know if we do not want this and I'll remove it
> Associations heatmaps: add column label for download

- apps/genetics/public/profiles/default.js
- apps/genetics/public/profiles/profile-partners.js
- apps/genetics/src/components/ErrorBoundary.jsx
- apps/platform/public/profiles/default.js
- apps/platform/public/profiles/profile-partners.js
- apps/platform/src/components/ErrorBoundary.jsx
Short PR to update the error message seen when a widget fail in both platform and genetics, as per issue https://github.com/opentargets/issues/issues/2823
Public platform handles also the version for PPP.
> Remove helpdesk email from widget error fallback (lf-error-message)

- apps/platform/src/sections/target/GeneticConstraint/GeneticConstraintTable.jsx
This PR addresses issue https://github.com/opentargets/issues/issues/2817. It updates the label in the Genetic Constraint widget (target profile page) based on the type of category:
so for the "pLoF" row, the last column reads "pLI=..." instead of "Z=..." like for the other rows.
> Update constraint metrics label

- apps/genetics/src/sections/api-page/SampleQueries/SampleQueries.jsx
[x] Removed `studiesAndLeadVariantsForGene`  GraphQL sample query from Genetics API Page.
[x] Part of issue: https://github.com/opentargets/issues/issues/2791
> remove studiesAndLeadVariants query from API page

- apps/genetics/src/pages/StudyLocusPage/Header.jsx
This PR makes the study and variant links in the study locus page header relative by removing the domain.
> Remove domain from study and variant link on study locus page

- apps/genetics/src/sections/variant/PheWASSection/ForestPlot.jsx
In Firefox browser there are a few issues with the forestplot:
- bottom axis (bottomRow) of the forestplot is not displayed correctly
- svg is displayed at the wrong point as its 'top' style is not taken into account
- font size of axis title was not taken into account
All these issues were caused by the fact that chrome correctly implies 'px' after style statements where needed, but firefox does not. So I added px in the styles of the points aforementioned.
> Fix display of forestplot in firefox browser

- apps/platform/index.html
- apps/platform/src/components/OpenTargetsTitle.jsx
- apps/platform/src/pages/DownloadsPage/DownloadsPage.jsx
In PPP the application name in the navbar should be: **Open Targets** Partner Preview Platform
**Issue:** https://github.com/opentargets/issues/issues/2889
**Deploy preview:** https://deploy-preview-100--ot-platform.netlify.app/
> [Platform]: PPP display correct app name on nav

- packages/ui/src/AutocompleteSearch.jsx
- packages/ui/src/Search/SearchInput.jsx
- packages/ui/src/Search/SearchListItem.jsx
- packages/ui/src/utils/searchUtils.js
**Issue:** # https://github.com/opentargets/issues/issues/2882
**Deploy preview:** https://deploy-preview-98--ot-platform.netlify.app/
> [Platform]: Search homepage shortcut bug

- apps/platform/index.html
- apps/platform/src/config.js
- apps/platform/src/pages/ProjectsPage/ProjectsPage.jsx
- apps/platform/src/pages/ProjectsPage/projects-data.json
**Issue:** # [Issue-2900](https://github.com/opentargets/issues/issues/2900)
**Deploy preview:** [PPP Preview](https://deploy-preview-107--ot-platform.netlify.app/projects)
* Test A: Text on table header is "Integrates into PPP", ppp documentation link on projects page redirects to [platform-docs](https://platform-docs.opentargets.org/partner-preview-platform).
* Test B: Text on table header is "Currently integrates into PPP", ppp documentation link on projects page redirects to [ot-home/ppp-doc](http://home.opentargets.org/ppp-documentation).
> [Platform]: PPP Project table header and icon changes

- package.json
- tsconfig.json
- yarn.lock
This PR adds the typescript dependency and a tsconfig. the tsconfig is related to my experience on other projects. It uses strict, but turns off noImplicitAny which is useful while developing. Tightening up strictness can make noImplicitAny:true again. I can explain various other elements of the tsconfig if interested. I also add the @types/file-saver, as file-saver is used in other parts of the app
https://github.com/opentargets/issues/issues/2871
https://github.com/opentargets/issues/issues/2857
Dependencies and config files
N/A
> [AppConfig]: Add Typescript support and config files

- apps/platform/src/pages/DownloadsPage/DownloadsPage.jsx
**Issue:** # [Issue-2899](https://github.com/opentargets/issues/issues/2899)
**Deploy preview:** [Preview](https://deploy-preview-106--ot-platform.netlify.app)
* Test A: Searching 'evidence' in data downloads table search was adding additional chips to first row every time search was done.
* Test B: Search 'evidence' in data downloads table.
> [Platform]: Data download table format multiplier

- apps/genetics/src/components/AssociatedStudiesTable.jsx
- apps/genetics/src/sections/gene/L2GPipeline/L2GPipelineQuery.gql
[Genetics]: update gene's L2G pipeline query with missing download fields
The PR adds the `study.nCases` field to the query for the gene's page "Associated studies: locus-to-gene pipeline" table. This fixes the corresponding column in the downloaded table, which was always empty.
**Issue:** [issue 2926](https://github.com/opentargets/issues/issues/2926)
**Deploy preview:** [link](https://deploy-preview-119--ot-genetics.netlify.app)
> [Genetics]: update gene's L2G pipeline query with missing download fields

- apps/platform/src/components/BasePage.jsx
- apps/platform/src/pages/HomePage/HomePage.jsx
- packages/ui/src/AutocompleteSearch.tsx
- packages/ui/src/GlobalSearch.jsx
**Deploy preview:** [genetics-preview](https://deploy-preview-123--ot-genetics.netlify.app)
- Bug fix (non-breaking change which fixes an issue)
- Test: 
1. Open genetics.
2. Click on search and type something.
3. There should be **NO** option named "Search for < term you entered >".
4. Clicking enter should open first result by default.
> [Genetics]: Search result page option disabled

- packages/ui/src/Footer.tsx
This PR addresses two small code problems in `Footer` component: these were introduced with the recent adding of the CC0 license. Note: these are only "code problems" flagged in the editor, no build or runtime JS errors. But it's still nice to refactor them.
1. defines a type for the `children` prop in the `FooterSection` element in the `Footer` component
2. remove the `rel` and `property` attributes in `Link` as these are not actually included in the generated html
**Issue:** no issue available
**Deploy preview:** not available (no Netlify build)
> [Package]: fix Footer tsx and props problems

- apps/platform/src/pages/HomePage/PPHomePage.jsx
- apps/platform/src/pages/HomePage/Version.jsx
In the prod version the homepage link to release notes is pointing to public release notes
- Check the home page in PPP mode
> [Platform]: fix PPP release version

- apps/platform/src/sections/evidence/Reactome/Body.jsx
- apps/platform/src/sections/evidence/SysBio/Body.jsx
- apps/platform/src/sections/evidence/UniProtLiterature/Body.jsx
- apps/platform/src/sections/evidence/UniProtVariants/Body.jsx
Refactor vars deconstruct in SysBio widget to fix error: undefined `ensgId` triggers error in `dataDownloaderFileStem` prop which causes the widget and page to crash.
It was noted that the evidence page breaks on PPP
> Can anyone double check this page on PPP: https://partner-platform.opentargets.org/evidence/ENSG00000080815/MONDO_0004975
> (https://opentargets-dev.slack.com/archives/C02B9NT33AL/p1683632137597549)
The error is due to an undefined var in the SysBio widget: this was fixed and the same approach applied to other widgets for consistency.
.../SysBio/Body.js = fixes for the actual bug + some style formatting
other files in PR = updated for consistency
This **PR does not** update the `dataDownloaderFileStem`: incorrectly this says "otgenetics", but since most widgets are like …
> [Platform / PPP ] fix SysBio/Gene Signature evidence widget IDs variables

- packages/ui/src/AutocompleteSearch.tsx
- packages/ui/src/Search/SearchInput.tsx
**Issue:** # [issue-2947](https://github.com/opentargets/issues/issues/2947)
* Test A: 
Steps to reproduce the behaviour:
1. Go to https://platform.opentargets.org/
2. Click on Search
3. See error (if you have any recent items)
> [Package]: Search dropdown bug

- apps/platform/.env
- apps/platform/src/pages/TargetPage/ProfileHeader.jsx
- apps/platform/src/pages/TargetPage/TargetDescription.jsx
Display a chip with "core essential gene" below the description section on the target profile page, based on the `target.isEssential` field. Note this field will be available in the API soon, however it's not there yet and it's therefore not possible to test this correctly at the moment.
**Issue:** https://github.com/opentargets/issues/issues/2917
**Deploy preview:** https://deploy-preview-151--ot-platform.netlify.app/
This has been tested locally by forcing a flag to display the chip. A screenshot is included in the ticket.
> [Platform] Add chip for gene essentiality to target description

- apps/platform/src/sections/drug/DrugWarnings/Body.jsx
**Issue:** # https://github.com/opentargets/issues/issues/2943
**Deploy preview:** https://deploy-preview-159--ot-platform.netlify.app/drug/CHEMBL1233
* Test A : New column and link to warning column added in drug warning table.
> [Platform]: Update drugWarnings annotation in the Platform

- apps/genetics/src/components/ManhattansVariantsTable.jsx
- apps/genetics/src/ot-ui-components/components/OtTableRF.jsx
The "Top Ranked Genes" in the `CSV` and `TSV` download files from the table on the study-comparison page (https://genetics.opentargets.org/study-comparison/GCST002222) show as `[object Object]`. 
This PR fixes this issue by using `OtTableRF` (instead of `OtTable`) in combination with the `DataDownloader`.
This minor change allowed to make a distinction between the data in the table (`dataWithCytoband`) and the data that is actually downloaded (`downloadData`). The "Top Ranked Genes" (or `bestGenes`) in `downloadData` contains a string of gene symbols instead of objects.
> [Genetics]: Fix download table on study-comparison page

- apps/platform/src/client.js
In the association tables, sometimes a bug appears where the first value in a column is shown for all the subsequent rows. When this happens, the API returns the correct information, but the response (`data`) of the `TargetAssociationsQuery`/`DiseaseAssociationsQuery` by the `client` defined in `client.js` returns the score of the first `ScoredComponent` for each datatype for all rows, see below. By explicitly caching the `ScoredComponent`s on `componentId` and `score` this was solved.
> [Platform] Specify caching of ScoredComponents in AOTF table

- apps/platform/src/sections/evidence/OTGenetics/Body.jsx
As per title, change the look of the link to a chip in the OT Genetics evidence widget "QTL effect" column. Also show empty cell instead of "N/A".
**Issue:** no issue
**Deploy preview:** https://deploy-preview-172--ot-platform.netlify.app/evidence/ENSG00000167207/EFO_0000384
> [Platform]: add chip style to QTL column in OT Genetics evidence widget

- apps/platform/src/sections/evidence/UniProtVariants/Body.jsx
Update UniProt Variants evidence widget: add column with chip linkout to ProtVar website.
**Issue:** no issue available
**Deploy preview:** https://deploy-preview-175--ot-platform.netlify.app/evidence/ENSG00000167207/EFO_0000384
> [Platform]: add ProtVar chip link to Uniprot Variants widget

- apps/platform/src/components/LabelChip.jsx
- apps/platform/src/constants.js
- apps/platform/src/sections/evidence/EVA/Body.jsx
- apps/platform/src/sections/evidence/OTGenetics/Body.jsx
- apps/platform/src/sections/evidence/UniProtVariants/Body.jsx
Update Open Targets Genetics, ClinVar and UniProt Variant evidence widgets: 
- functional consequence changes to variant consequence
- chip links change style and add tooltip and label
**Issue:** not available
**Deploy preview:** https://deploy-preview-178--ot-platform.netlify.app
> # [Platform]: Update functional consequence to variant consequence with label-chip

- apps/platform/src/sections/disease/Phenotypes/Body.jsx
- apps/platform/src/sections/drug/DrugWarnings/Body.jsx
**Issue:** # [2923](https://github.com/opentargets/issues/issues/2923)
**Deploy preview:** https://deploy-preview-177--ot-platform.netlify.app/disease/EFO_0001064
> [Platform]: Null check added for clinical signs

- apps/platform/src/sections/drug/DrugWarnings/Body.jsx
Change columns of Drug Warnings
**Issue:** # [(link)](https://github.com/opentargets/issues/issues/3002)
- Check deploy preview in `/drug/CHEMBL122`
> [Platform]: Drug page remove EBI_OLS url and Meddra

- apps/platform/src/sections/evidence/CRISPRScreen/Body.jsx
- apps/platform/src/sections/evidence/OTCRISPR/Body.jsx
Update the `Significance` column in PPP ot-crispt widget: add tooltip for the `statisticalTestTail` field (similarly to the cirspr-screen widget).
**Issue:** no issue available
> [Platform]: add tooltip for testtail to ot-crispr widget

- apps/platform/src/sections/evidence/OTValidation/Body.jsx
- Go to evidence  `/target/ENSG00000165392/associations` sort by validation lab, see results
> [Platform]: Validation CRISPR not showing significance indicator 

- apps/platform/src/components/ExternalLink/CrisprDepmapLink.jsx
Adjust the size of the depmap link help icon on target page
MUI5 caused the help icon for "Project Score" (DepMap) on target page to display too big. However the one in production looks very small. 
Resetting the size to be the same as the label text (then the `<sup>` tag element makes it a little smaller)
**Issue:** N/A
**Deploy preview:** https://deploy-preview-209--ot-platform.netlify.app/
> [Platform]: resize depmap link help icon on target page

- apps/platform/src/components/AssociationsToolkit/Table/CellName.jsx
> [Platform]: AotF pinned rows fix css class

- packages/sections/src/common/Literature/Entities.jsx
- packages/sections/src/components/PublicationsDrawer/PublicationWrapper.jsx
- packages/sections/src/evidence/EuropePmc/Publication.jsx
Adjust alignment of buttons and spacing between chips. Also sets the color for the "show abstract" button.
Note: this does not address the incorrect alignment of the download buttons in the evidence literature widget.
**Issue:** N/A
**Deploy preview:** https://deploy-preview-218--ot-platform.netlify.app/
> [Platform]: Adjust spacing and alignment in bibliography and literature widgets

- packages/sections/src/components/Table/Table.jsx
- packages/sections/src/target/Expression/SummaryTab.jsx
- packages/ui/src/components/Search/SearchListItem.tsx
> [Platform]: data downloader in middle 

- apps/platform/src/theme.js
- packages/ui/src/ThemeProvider/defaultTheme.ts
Update the tabs component: 
- disable ripple effect; 
- disable animation when selecting tab; 
- no text transformation (i.e. no all uppercase). 
Updated in `theme`. `default theme` also updated.
Could try and update the style to look more like current production platform.
**Issue:** N/A
**Deploy preview:** https://deploy-preview-222--ot-platform.netlify.app/
> [Platform]: update tabs component style

- packages/ui/src/components/Search/utils/searchUtils.ts
> [Platform]: delete description key from search object

- packages/sections/src/drug/KnownDrugs/KnownDrugsQuery.gql
- packages/sections/src/target/KnownDrugs/KnownDrugsQuery.gql
Changing the table page size causes the table to show no data when paginating. Adding `size` parameter to query fixes it.
Setting the default to 10 as on disease profile page.
**Issue:**
> [Platform]: fix known drugs table missing data when change page size

- packages/ui/src/components/Table/TablePaginationActions.jsx
> [Platform]: fix table pagination icons size

- packages/sections/src/drug/AdverseEvents/Body.jsx
Pass the `pageSize`, as selected in dropdown menu, to the query.
**Issue:** N/A
**Deploy preview:** https://deploy-preview-240--ot-platform.netlify.app/drug/CHEMBL112
> [Platform]: fix changing page size in pharmacovigilance widget

- packages/sections/src/disease/OTProjects/Body.jsx
- packages/sections/src/disease/OTProjects/OTProjectsQuery.gql
- packages/sections/src/disease/OTProjects/OTProjectsSummaryFragment.gql
> [Platform]: OT Projects Section query different from fragment 

- packages/ui/src/components/PublicationsDrawer/PublicationWrapper.jsx
Update the text for "Full text available" chip in the publications drawer.
Still in progress - @buniello will check if the proposed solution works.
**Issue:** https://github.com/opentargets/issues/issues/3008
**Deploy preview:** https://deploy-preview-250--ot-platform.netlify.app
> [Platform]: add more detailed "full text available" description to publications

- apps/platform/src/pages/DiseasePage/Header.jsx
This PR updates the EFO link at the top of the disease page. This still needs to be reviewed to confirm it's the behaviour we want.
It simply updates the link to OLS v4. To my understanding it's not currently supported by identifiers.org - so we'll need to review this.
EDIT 25/10/2023: @DSuveges and @ireneisdoomed have reviewed the approach and so the proposed solution (updating the OLS URL) is accepted. We can review and merge
**Issue:** https://github.com/opentargets/issues/issues/3108
**Deploy preview:** https://deploy-preview-278--ot-platform.netlify.app/
> [Platform]: Update EFO link in disease page header

- packages/sections/src/target/ChemicalProbes/Body.jsx
The Chemical Probes widget table, on the target profile page, used to have a "custom" sorting. This PR adds back more accurate sorting based on score, quality and origin. @ireneisdoomed can confirm if this approach is suitable and the results are OK.
Note: this is an old ticket, so not high priority. Need to confirm expected functionality before code review.
**Issue:** # https://github.com/opentargets/issues/issues/2742
**Deploy preview:** https://deploy-preview-279--ot-platform.netlify.app/
See Chemical Probes widget at below link; probes with the same score should be prioritised by quality and origin:
> [Platform]: add custom sorting to the chemical probes table

- apps/platform/src/utils/urls.js
- packages/sections/src/utils/urls.js
- packages/ui/src/utils/urls.js
Update the clinicaltrials base URL in the platform config (urls.js file); this seems to only be used in the Indications widget on drug profile page. 
Hence it appears that only packages/sections/src/utils/urls.js is being used: might need to review the use of the other two files.
Note: ClinicalTrials now uses a correct redirect from the old URLs so this fix might no longer be strictly required.
Also, if the URL will come from the API, this fix will also need to be updated accordingly.
**Issue:** https://github.com/opentargets/issues/issues/3048
Check the inications widget on any drug profile page and see the link in the last column:
> [Platform]: update clinicaltrials URL in config

- packages/sections/src/evidence/OTValidation/Body.jsx
**Issue:** https://github.com/opentargets/issues/issues/3103
> [Platform]: OTVL padding tooltip fix

- apps/platform/src/pages/DiseasePage/DiseasePage.jsx
- apps/platform/src/pages/DrugPage/DrugPage.jsx
- apps/platform/src/pages/TargetPage/TargetPage.jsx
**Issue:** # https://github.com/opentargets/issues/issues/3150
> [Platform]: Dynamic route fallback

- apps/platform/src/pages/DownloadsPage/dataset-mappings.json
co-occurences only go to FTP (no frontend, no Big Query)
edited order numbers accordingly
> [Platform]: Added EPMC co-occurences and tissue specificity to list

- apps/platform/src/components/AssociationsToolkit/CopyUrlButton.jsx
- apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx
- apps/platform/src/components/AssociationsToolkit/utils/downloads.js
- apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.jsx
- apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociations.jsx
**Issue:** # https://github.com/opentargets/issues/issues/3153
> [Platform]: Aotf export pinned data

- apps/platform/src/components/AssociationsToolkit/static_datasets/prioritisationColumns.ts
**Issue:** # https://github.com/opentargets/issues/issues/3156
> [Platform]: Target prioritisation links updated

- apps/platform/src/App.tsx
- apps/platform/src/pages/HomePage/HomePage.jsx
- apps/platform/src/pages/HomePage/PPHomePage.jsx
- apps/platform/src/pages/HomePage/index.jsx
- apps/platform/src/utils/global.js
> [Platform]: Homepage crash sharing parameter by value

- packages/sections/src/evidence/Chembl/Body.jsx
- packages/sections/src/evidence/Chembl/ChemblQuery.gql
- packages/sections/src/evidence/Chembl/index.js
- packages/sections/src/evidence/EVASomatic/Body.jsx
- packages/sections/src/evidence/EVASomatic/EvaSomaticQuery.gql
- packages/sections/src/evidence/EVASomatic/index.js
- packages/sections/src/evidence/Impc/Body.jsx
- packages/sections/src/evidence/Impc/sectionQuery.gql
**Issue:** https://github.com/opentargets/issues/issues/3147
- Check Chembl section on AotF
- Check IMPC section on AotF
- Check ClinVar section on AotF
> [Platform]: Migrate Chembl, IMPC and ClinVar Somatic to server side pagination

- packages/sections/src/evidence/Chembl/ChemblSummaryFragment.gql
- packages/sections/src/evidence/Chembl/Summary.jsx
- packages/sections/src/evidence/EVASomatic/EvaSomaticSummary.gql
- packages/sections/src/evidence/EVASomatic/Summary.jsx
Evidence page crashing due to wrong object destruction 
- Check any evidence page
> [Platform]: correct fragment section variables

- apps/platform/src/App.tsx
- apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx
- apps/platform/src/pages/HomePage/Version.jsx
- packages/ui/src/contexts/ConfigurationProvider.tsx
- packages/ui/src/index.tsx
To enforce development experience and code quality, we should unify the data version and client import from one source of truth. This PR creates a new ConfigurationProvider with a hook (useConfigContext) that exposes a data version and ApolloClient instance.
**Issue:** https://github.com/opentargets/issues/issues/3165
- Check home page data version
- Check AotF exported file name with version
> [Platform]: Create configuration provider - migrate version requests to hook

- apps/platform/src/components/AssociationsToolkit/DataUploader/DataUploader.jsx
> [Platform]: Adding docs link to aotf upload 

- packages/sections/src/target/Expression/GtexTab.jsx
GTEx tab was broken because the API was outdated (v1). Updated target page to use the GTEx API v2.
Breaking change (fix or feature that would cause existing functionality to not work as expected)
Ran yarn dev:platform locally
> [Platform]: Updated GTEx API calls to v2 on target page

- packages/ui/src/components/GlobalSearch/utils/searchUtils.js
**Issue:** # https://github.com/opentargets/issues/issues/3182
> [Platform]: added null check for search response keys

- apps/platform/src/pages/DownloadsPage/DownloadsSchemaDrawer.jsx
**Issue:** # https://github.com/opentargets/issues/issues/3180
**Deploy preview:** https://deploy-preview-321--ot-platform.netlify.app/downloads
> [Platform]: Downloads schema map type fix

- apps/platform/src/components/AssociationsToolkit/CopyUrlButton.jsx
- apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx
- apps/platform/src/components/AssociationsToolkit/context/AssociationsContext.jsx
- apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.jsx
- apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociations.jsx
- packages/ui/src/components/ApiPlaygroundDrawer.jsx
- packages/ui/src/components/ApiPlaygroundDrawer.tsx
- packages/ui/src/components/Table/DataDownloader.jsx
- packages/ui/src/index.tsx
Extracting the component from DataDownloader.jsx and creating a separate component ApiPlaygroundDrawer.jsx and using in original component and in aotf pages.
**Issue:** # https://github.com/opentargets/issues/issues/3199
> [Platform]: Adding api query playground to aotf 

- apps/platform/src/components/AssociationsToolkit/Table/TableBody.jsx
Platform: Don't close data widget in association table if clicked on Graphiql autocomplete
If a data widget is opened on the Association page, and the Graphiql tool is opened, if clicking on a Graphiql autocomplete it will close the complete data widget. This is because the "ClickAway" handler detects a click "away" from the data widget. (My colleague Anika Bongaarts found this bug). 
- [ x] My changes generate no new warnings
>  [Platform]: AotF Prevent data widget closing if clicked on GraphiQL

- packages/sections/src/drug/Pharmacogenomics/Body.jsx
- packages/sections/src/target/Pharmacogenomics/Pharmacogenomics.gql
- packages/sections/src/target/Pharmacogenomics/PharmacogenomicsTable.jsx
#[Platform]: Pharmacogenetics is direct target column added
A new column added to Pharmacogenetics widget on both drug and target page.
**Issue:** # https://github.com/opentargets/issues/issues/3202
> [Platform]: Pharmacogenetics is direct target column added

- packages/sections/src/evidence/OTCRISPR/Body.jsx
- packages/sections/src/evidence/OTEncore/Body.jsx
Adding api query option to ppp specific section (CRISPR and ENCORE)
**Issue:** # https://github.com/opentargets/issues/issues/2870
> [Platform]: query param passed  for api playground

- apps/platform/src/pages/APIPage/DrugAnnotation.gql
- packages/sections/src/drug/DrugWarnings/DrugWarningsQuery.gql
Remove mapping between drug warning and MedDRA, from widget and from sample query.
**Issue:** # https://github.com/opentargets/issues/issues/3003
**Deploy preview:** https://deploy-preview-337--ot-platform.netlify.app/
> [Platform]: Remove mapping between drug warning and MedDRA

- packages/sections/src/common/Literature/DateFilter.tsx
When the API response had no literature results and the earliest pub date was 0 we were seeing a value of 0 in the labels. This negatively impacts the user experience. It was decided that in this case we should display the value 'YYYY-MM'.
**Issue:** # [3233](https://github.com/opentargets/issues/issues/3233)
**Deploy preview:** [link](https://deploy-preview-341--ot-platform.netlify.app/disease/MONDO_0018997)
> [Platform]: Update DateFilter labels

- packages/sections/src/common/Literature/DateFilter.tsx
There was an issue with the months calculation where a month was being subtracted and that was causing an issue with the higher limit of the filter
**Issue:** # [2578](https://github.com/opentargets/issues/issues/2578)
> [Platform]: Update higher limit calc

- packages/sections/src/common/Literature/DateFilter.tsx
There was a case when the date filter was updated and the results weren't being shown. This was because the cursor wasn't being cleaned after the filter had changed
**Issue:** # [2578](https://github.com/opentargets/issues/issues/2578)
**Deploy preview:** [link](https://deploy-preview-353--ot-platform.netlify.app)
> [Platform]: Clean cursor when date filter changes.

- apps/platform/src/components/AssociationsToolkit/AotfApiPlayground.tsx
- apps/platform/src/components/AssociationsToolkit/DataDownloader.jsx
- apps/platform/src/components/AssociationsToolkit/index.js
- apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.jsx
- apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociations.jsx
Moving aotf playground to separate component to use advantage of aotf context instead of props.
**Issue:** # https://github.com/opentargets/issues/issues/3290
**Deploy preview:** https://deploy-preview-363--ot-platform.netlify.app/
> [Platform]: Moving aotf playground to another component

- packages/sections/src/target/Expression/GtexVariability.jsx
Mouseover functionality in the Gtex tab wasn't working due to `this` not being bound to the DOM element of the D3 event handler, returning a null value. Updated arrow function to match D3 v5 syntax used by ot-ui-apps  (https://devdocs.io/d3~5/d3-selection#selection_on)
**Issue:** NA
**Deploy preview:** NA
Check Gtex tab of random entries and hover over boxplots
> [Platform] Fix Gtex mouseover feature

- packages/ui/src/components/ExternalLink/TepLink.tsx
Migrate the TepLink component to TypeScript.
> [Package]: migrate TepLink component to TypeScript

- packages/sections/src/variant/UniProtVariants/Body.tsx
- packages/sections/src/variant/UniProtVariants/Description.tsx
Removed reported protein column (since all rows the same) and updated UniProt link in widget description so that specific to the protein.
Checked in dev environment.
- [] I have commented my code, particularly in hard-to-understand areas
> [Platform]: Remove reported protein column from UniProt widget in variant page 

- packages/sections/src/common/KnownDrugs/SourceDrawer.jsx
- packages/sections/src/constants.js
- packages/sections/src/utils/urls.js
**Issue:**  https://github.com/opentargets/issues/issues/3348
- Check multiple drug page
> [Platform]: prevent drug widgets from crashing by new references

- apps/platform/src/pages/VariantPage/Profile.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Description.tsx
- packages/sections/src/variant/QTLCredibleSets/Summary.tsx
- packages/sections/src/variant/QTLCredibleSets/index.ts
Add QTL credible sets widget to variant page.
Checked in dev environment.
> [Platform] Add QTL credible sets widget to variant page

- apps/platform/src/components/AssociationsToolkit/components/Table/CellName.jsx
Disable interactors link in AotF view
> [Platform]: disable interactors link in `AotF`

- apps/platform/src/components/AssociationsToolkit/components/Table/TableBody.jsx
Add empty message on AotF no data
- Navigate to AotF -> filter until no results
> [Platform]: add empty AotF message

- apps/platform/src/components/AssociationsToolkit/components/SearchInput.jsx
- apps/platform/src/components/AssociationsToolkit/index.ts
- apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociations.tsx
- apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociations.tsx
Conditionally display `SearchInput` or `FacetsFilters` components.
- Check disease associations page
- Check target associations page
> [Platform]: Rollback `AotF` search input in public

- packages/sections/src/disease/Phenotypes/Body.jsx
Optional chaining added to known drugs column to avoid widget crashing when data/required data is not there.
**Deploy preview:** https://deploy-preview-402--ot-platform.netlify.app/disease/MONDO_0010831
> [Platform]: Optional chaining added to known drugs column

- packages/sections/src/variant/UniProtVariants/Description.tsx
Add Uniprot id to Uniprot description link.
Tested link in dev.
> [Platform] Add Uniprot id to Uniprot description link

- packages/ui/src/components/GlobalSearch/GlobalSearchInput.tsx
Migrate the GlobalSearchInput component to TypeScript.
> [Package]: migrate GlobalSearchInput component to TypeScript

- apps/platform/src/components/AssociationsToolkit/hooks/useAssociationsData.js
Fix navigation to AotF when url `?table=prioritisations`
- Navigate to `/disease/MONDO_0001627/associations?table=prioritisations`
> [Platform]: aotf crash on prioritisation url

- apps/platform/src/pages/DiseasePage/DiseaseAssociations/DiseaseAssociationsQuery.gql
- apps/platform/src/pages/TargetPage/TargetAssociations/TargetAssociationsQuery.gql
- packages/ui/src/components/Link.tsx
As AggregationFilter was removed from the API, it needs to be removed from the UI queries
**Issue:** https://github.com/opentargets/issues/issues/3360
- Check target associations
- Check disease associations
> [Platform]: remove aggregation filter from AotF

- packages/sections/src/variant/InSilicoPredictors/Body.tsx
Minor improvements to variant page insilico predictors widget:
- handle missing `score`
- pass data into `renderBody` function
- use `columns` array rather than `getColumns` function since sufficient
> [Platform] Minor improvements to variant page insilico predictors widget 

- packages/sections/src/variant/VariantEffectPredictor/Body.tsx
- packages/sections/src/variant/VariantEffectPredictor/VariantEffectPredictorQuery.gql
Update VEP widget to reflect API changes:
- sort on `transcriptIndex`
- add `consequenceScore` column
- remove predictors columns (since mostly `null`)
- replace old `distance` column with the 2 new distance columns
**Issue:** [#3386](https://github.com/opentargets/issues/issues/3386)
Checked on dev
> [Platform]: Update VEP widget on variant page

- apps/platform/src/pages/VariantPage/Header.tsx
- packages/sections/src/variant/InSilicoPredictors/Body.tsx
- packages/sections/src/variant/InSilicoPredictors/Description.tsx
- packages/sections/src/variant/InSilicoPredictors/InSilicoPredictorsQuery.gql
- packages/sections/src/variant/VariantEffectPredictor/Body.tsx
- packages/sections/src/variant/VariantEffectPredictor/Description.tsx
- packages/sections/src/variant/VariantEffectPredictor/VariantEffectPredictorQuery.gql
- packages/ui/src/components/DisplayVariantId.tsx
- packages/ui/src/components/Section/SectionItem.jsx
- packages/ui/src/index.tsx
Add `DisplayVariantId` component and use it where show variant id - currently in variant page header and section descriptions.
The PR includes small changes to `packages/ui/src/components/Section/SectionItem.jsx`:
* Bug fix: check if have data before passing it to `renderDescription` function - and show a skeleton if not.
* Use a `<div>` rather than `<p>` for the description subheader to avoid DOM nesting warnings from MUI.
**Issue:** [3390](https://github.com/opentargets/issues/issues/3390)
**Preview:** https://deploy-preview-441--ot-platform.netlify.app/variant/OTVAR_1_109607656_cc1bda57abafe82ac6cb5ec620a02a19
> [Platform]: Add DisplayVariantId component

- packages/sections/src/target/DepMap/DepmapPlot.jsx
I think "Dependency" is more appropriate than "Unfavourable" in the widget context.
Not tested
> [Platform]: rename legend in Cancer DepMap widget

- packages/ui/src/components/EllsWrapper.tsx
Migrate the EllsWrapper component to TypeScript.
> [Package]: migrate EllsWrapper component to TypeScript

- packages/sections/src/target/DepMap/Description.jsx
Updated the DepMap widget description (gene essentiality) to include the target symbol, so that screenshots would reflect which target they represent.
Tested on my local computer in the target prioritisation view and the target profile page.
> [Platform]: Changed DepMap widget description to include the target symbol

- apps/platform/src/pages/StudyPage/Profile.tsx
- apps/platform/src/pages/StudyPage/ProfileHeader.tsx
- apps/platform/src/pages/StudyPage/StudyPage.tsx
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/Description.tsx
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsQuery.gql
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
- packages/sections/src/study/QTLCredibleSets/Summary.tsx
- packages/sections/src/study/QTLCredibleSets/index.ts
Add QTL credible sets widget to study page.
**Issue:** [#3377](https://github.com/opentargets/issues/issues/3377)
**Deploy preview: https://deploy-preview-465--ot-platform.netlify.app/study/GTEx_adipose_subcutaneous_ENSG00000189337.17_1_13892792_13893756**
> [Platform]: Add QTL credible sets widget to study page

- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsQuery.gql
- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsSummaryFragment.gql
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsQuery.gql
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
- packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsQuery.gql
- packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsSummaryFragment.gql
- packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql
- packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
Use page parameter in credible sets queries.
Allows us to see all credible sets in all (or almost all) cases for now though widgets will likely be changed to server side pagination in future.
> [Platform]: Use page parameter in credible sets queries

- apps/platform/src/pages/VariantPage/ProfileHeader.tsx
Allow greater precision in allele frequency plot at top of variant page.
**Deploy preview:** https://deploy-preview-480--ot-platform.netlify.app/variant/11_64600382_G_A
> [Platform]: Allow greater precision in allele frequency plot

- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Include variant id in column header tooltips for posterior probabilities and r^2 in variant page credible sets widgets.
Checked in dev.
> [Platform]: Include variant id in credible sets tooltips

- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsQuery.gql
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsQuery.gql
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsQuery.gql
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql
Add links from credible sets widgets to credible set page.
**Issue:** [#3436](https://github.com/opentargets/issues/issues/3436)
> [Platform] Add links from credible sets widgets to credible set page

- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Handle missing biosample in molQTL credible sets widget on variant page.
**Issue:**
Checked on dev
> [Platform]: Handle missing biosample in molQTL credible sets widget on variant page

- packages/ui/src/components/Header.tsx
Migrate the Header component to TypeScript.
**Condition:** Loading
**Condition:** Loaded
> [Package]: migrate Header component to TypeScript

- packages/ui/src/components/Highlights.tsx
Migrate the Highlights component to TypeScript.
> [Package]: migrate Highlights component to TypeScript

- packages/ui/src/components/HeaderMenu.tsx
Migrate the HeaderMenu component to TypeScript.
**Condition:** Menu closed
**Condition:** Menu opened
> [Package]: migrate HeaderMenu component to TypeScript

- packages/sections/src/credibleSet/GWASColoc/GWASColocQuery.gql
- packages/sections/src/credibleSet/GWASColoc/GWASColocSummaryFragment.gql
Increase max rows in coloc widget from 25 to 250.
Note: this table will be server paginated in future since it will often have a very large number of rows.
**Issue:** [#3510](https://github.com/opentargets/issues/issues/3510)
**Deploy preview:** https://deploy-preview-502--ot-platform.netlify.app/credible-set/-8771774904770677429
> [Platform] Increase max rows in coloc widget

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/Variants/Body.tsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/utils/comparators.ts
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Use dedicated comparator for p-values in genetics widgets (supplied as mantissa and exponent) so get correct results even when values are very small. 
**Deploy preview:** https://deploy-preview-500--ot-platform.netlify.app/variant/12_21178615_T_C
> [Platform]: Accurate sorting when very small p-values

- apps/platform/src/pages/VariantPage/Profile.tsx
- packages/sections/src/variant/EVA/EVASummaryFragment.gql
- packages/sections/src/variant/EVA/Summary.tsx
- packages/sections/src/variant/EVA/index.ts
- packages/sections/src/variant/UniProtVariants/Body.tsx
- packages/sections/src/variant/UniProtVariants/Description.tsx
- packages/sections/src/variant/UniProtVariants/Summary.tsx
- packages/sections/src/variant/UniProtVariants/UniProtVariantsQuery.gql
- packages/sections/src/variant/UniProtVariants/UniProtVariantsSummaryFragment.gql
- packages/sections/src/variant/UniProtVariants/index.ts
Add uniprot widget to variant page.
**Deploy preview:** https://deploy-preview-507--ot-platform.netlify.app/variant/17_63945614_C_T
> [Platform]: Add uniprot widget to variant page

- packages/ui/src/components/Chip.tsx
- packages/ui/src/components/LongList.tsx
- packages/ui/src/components/ProfileHeader/ProfileChipList.tsx
Migrate the Description component to TypeScript.
**Condition:** loading, inline
**Condition:** loading, not inline
**Condition:** loaded, colapsed
**Condition:** loaded, expanded
> [Package]: migrate ProfileChipList to TypeScript

- packages/sections/src/target/DepMap/DepmapPlot.jsx
In firefox the tooltip of the depmap plot is rendered like this:
While in chrome the two linebreaks did not affect the front-end at all:
Therefore I just removed the linebreaks so it fixed the tooltip in firefox and kept the tooltip the same as it was in chrome.
- Test A tested locally in yarn
> [Platform]: Remove buggy formatting in DepMap tooltip

- apps/platform/src/components/AssociationsToolkit/static_datasets/dataSourcesAssoc.js
- apps/platform/src/sections/evidenceSections.js
- packages/sections/src/evidence/GWASCredibleSets/Body.jsx
- packages/sections/src/evidence/GWASCredibleSets/Description.jsx
- packages/sections/src/evidence/GWASCredibleSets/GWASCredibleSetsSummary.gql
- packages/sections/src/evidence/GWASCredibleSets/Summary.jsx
- packages/sections/src/evidence/GWASCredibleSets/index.js
- packages/sections/src/evidence/GWASCredibleSets/sectionQuery.gql
> [Platform]: add create GWAS credible sets to AotF and base widget

- packages/sections/src/variant/VariantEffectPredictor/Description.tsx
Transcript consequence widget description typo
> fix: typo in transcript consequence widget

- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsQuery.gql
Use first entry of `l2Gpredictions` for top L2G (instead of `strongestLocus2Gene`) in GWAS credible sets widget on study page.
**Issue:** [#3616](https://github.com/opentargets/issues/issues/3616)
> [Platform]: Use l2Gpredictions instead of strongestLocus2Gene in study page

- apps/platform/src/pages/HomePage/searchExamples.ts
Includes the search suggestions from OTG home page:
- Target PCSK9
- Variant 1_154453788_C_T
I showed the name of the variant as the RSID. Since none of the variant IDs are readable (as opposed to the other entities), it could showcase that you can search by using different IDs.
We can add other meaningful examples later on.
> feat: bring home search suggestions from OTG

- apps/platform/src/pages/CredibleSetPage/CredibleSetPage.gql
- apps/platform/src/pages/CredibleSetPage/CredibleSetPage.tsx
- apps/platform/src/pages/CredibleSetPage/Profile.tsx
- apps/platform/src/pages/StudyPage/Profile.tsx
- apps/platform/src/pages/StudyPage/StudyPage.gql
- apps/platform/src/pages/StudyPage/StudyPage.tsx
- packages/sections/src/credibleSet/GWASMolQTL/Body.tsx
- packages/sections/src/credibleSet/GWASMolQTL/Description.tsx
- packages/sections/src/credibleSet/GWASMolQTL/GWASMolQTLColocQuery.gql
- packages/sections/src/credibleSet/GWASMolQTL/GWASMolQTLSummaryFragment.gql
- packages/sections/src/credibleSet/GWASMolQTL/Summary.tsx
- packages/sections/src/credibleSet/GWASMolQTL/index.ts
**Issue:** https://github.com/opentargets/issues/issues/3510
- Check credible set page
> [Platform]: Credible-set page molQTL section

- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsQuery.gql
- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsSummaryFragment.gql
- packages/sections/src/study/GWASCredibleSets/ManhattanPlot.tsx
- packages/sections/src/study/GWASCredibleSets/index.ts
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsQuery.gql
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
- packages/sections/src/study/QTLCredibleSets/index.ts
Update study page to use `count` and `rows` for `CredibleSets` and `Loci` in the API.
**Deploy preview:** https://deploy-preview-546--ot-platform.netlify.app/study/GCST008338
Checked study page, example study IDs:
- GWAS credible sets: GCST008338
- molQTL credible sets: Cytoimmgen_ge_combined_CD4_Memory_UNS_16H_ENSG00000232300
> [Platform]: Update study page to reflect API changes

- packages/sections/src/credibleSet/Variants/Body.tsx
- packages/sections/src/credibleSet/Variants/VariantsQuery.gql
This widget accidentally only listed the lead variant instead of all variants in the credible set.
GraphQL query needed to be adjusted:
Dev:
This PR:
> fix:credible set listing all variants instead of only lead

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/GWASMolQTL/Body.tsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
This PR just standardises the navigate column icon. It can be changed later on but at least they are consistent now.
Two questions I might not be the best person to answer:
- Is there enough here to do an abstraction that is reused?
- There could be a problem with alignment. Content was centered and header untouched. It looked good in busy widgets but not to busy. Alignment is not totally consistent in this PR
> feat: consistent navigate button

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/GWASMolQTL/Body.tsx
It's not an expected situation, but it prevents the UI crashing given the current issues with the API responses
> fix: handle null study locus id in colocalisation widgets

- packages/sections/src/study/GWASCredibleSets/Body.tsx
GWAS credible sets widget was failing when no L2G target or score.
Checked on study page
> [Platform]: Replace unsafe destructuring assignments on study page

- packages/sections/src/evidence/OTGenetics/sectionQuery.gql
Query was crashing due to recent updates in API.
> fix: old genetics use variant object in query

- apps/platform/src/constants.js
- apps/platform/src/pages/CredibleSetPage/ProfileHeader.gql
- apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx
- packages/sections/src/constants.js
- packages/sections/src/evidence/GWASCredibleSets/Body.jsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/PheWasPlot.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Several improvements in the credible set metadata:
- stars added
- Locus in one row
- Publication in one row
- Sample size with comma
- Background trait added
- Several tooltips and fields renamed
A few examples:
> feat: credset page metadata improvements

- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
- packages/ui/src/components/PublicationsDrawer/SummaryLoader.jsx
- packages/ui/src/components/Section/SectionItem.tsx
Add loading message to credible sets widgets on variant page
**Deploy preview:** 
Checked on variant page
> [Platform]: Add loading message to credible sets widgets on variant page

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/GWASColoc/GWASColocQuery.gql
- packages/sections/src/credibleSet/GWASMolQTL/Body.tsx
- packages/sections/src/credibleSet/GWASMolQTL/GWASMolQTLColocQuery.gql
Add directionality column to coloc widgets
**Issue:** [#3617](https://github.com/opentargets/issues/issues/3617)
Checked on credible sets page.
> [Platform]: Add directionality column to coloc widgets

- apps/platform/src/pages/DiseasePage/Profile.jsx
- packages/sections/src/disease/GWASStudies/Body.tsx
- packages/sections/src/disease/GWASStudies/GWASStudiesQuery.gql
- packages/sections/src/disease/GWASStudies/index.ts
Batch load studies and use updated study api on disease page:
Checked on disease page - e.g. `disease/EFO_0004346`
> [Platform]: Batch load studies and use updated study api on disease page

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/GWASMolQTL/Body.tsx
- packages/sections/src/evidence/GWASCredibleSets/Body.jsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
- packages/ui/src/components/Navigate.tsx
- packages/ui/src/index.tsx
Use new `Navigate` component to harmonise appearance of navigation links and remove repeated code.
**Issue:** [#3629](https://github.com/opentargets/issues/issues/3629)
Checked on changed pages.
> [Platform]: Use new Navigate component

- packages/sections/src/credibleSet/Locus2Gene/Body.tsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
Add/harmonise l2g score tooltips in profile pages - leave tooltip in evidence as is.
**Issue:** [#3629](ithub.com/opentargets/issues/issues/3629)
Checked profile pages
> [Platform]: add/harmonise l2g score tooltips

- packages/sections/src/evidence/OTGenetics/Body.jsx
At the moment it was displayed as N/A all the time.
Now it will show the variant ID. There is a corner case in which the variant ID from old genetics is not used in our new variant index. In this case, I confirmed the variant ID will display the N/A.
> [Platform]: fix variant id displayed in old genetics widget

- packages/sections/src/evidence/UniProtVariants/Body.jsx
- packages/sections/src/evidence/UniProtVariants/UniprotVariantsQuery.gql
Based on suggestion from @DSuveges, adding variant ID with link to variant page in uniprot widget
Sorting by variant works, but I didn't implement sorting by amino acid consequence
With some help from @carcruz we also included the aminoacid consequence in a diifferent column
> [Platform]: feat variant id and amino acid consequence in uniprot widget

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/GWASColoc/GWASColocQuery.gql
- packages/sections/src/credibleSet/GWASColoc/GWASColocSummaryFragment.gql
- packages/sections/src/credibleSet/GWASColoc/index.ts
- packages/sections/src/credibleSet/Locus2Gene/Body.tsx
- packages/sections/src/credibleSet/Locus2Gene/Locus2GeneQuery.gql
- packages/sections/src/credibleSet/Locus2Gene/Locus2GeneQueryFragment.gql
- packages/sections/src/credibleSet/Locus2Gene/index.ts
- packages/sections/src/credibleSet/MolQTLColoc/Body.tsx
- packages/sections/src/credibleSet/MolQTLColoc/MolQTLColocQuery.gql
- packages/sections/src/credibleSet/MolQTLColoc/MolQTLColocSummaryFragment.gql
- packages/sections/src/credibleSet/MolQTLColoc/index.ts
Use batching for coloc widgets on credible sets page.
Includes updating the page to use the new API changes for `colocalisation` and `l2GPredictions`
Checked credible set page
> [Platform]: Use batching for coloc widgets on credible sets page

- packages/sections/src/credibleSet/Variants/Body.tsx
- packages/sections/src/credibleSet/Variants/VariantsQuery.gql
Use batching for variants widget on credible sets page.
Checked on credible set page.
> [Platform] Use batching for variants widget on credible sets page

- packages/sections/src/evidence/EVA/Body.jsx
- packages/sections/src/evidence/EVA/ClinvarQuery.gql
> [Platform]: use displayVariant comp on clinvar evidence

- apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx
- apps/platform/src/pages/StudyPage/StudyProfileHeader.gql
- apps/platform/src/pages/StudyPage/StudyProfileHeader.tsx
Adds project ID in credible set and study metadata only for QTL studies
This information was missing and can help understand where the QTL study is coming from
> [Platform]: feat add project id to study and credible set metadata when QTL studies

- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsQuery.gql
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql
Credible set size and posterior probabilities could not work in the same "locus" query.
This adds another "locus" query aliased
> [Platform]: fix credible set size in credible set widgets

- packages/sections/src/study/GWASCredibleSets/ManhattanPlot.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/PheWasPlot.tsx
- packages/ui/src/components/Plot/components/XLabel.jsx
- packages/ui/src/components/Plot/components/XTitle.jsx
- packages/ui/src/components/Plot/components/YLabel.jsx
Fixes for Manhattan plot (study page) and PheWas plot (variant page):
- Both plots
- switch to computing y values directly and using linear y-scale in plots - very small p-values (less than`Number.MIN_NUMBER`) and use of log scales was causing various issues
- use `dominant-baseline` instead of `alignment-baseline` with labels for consistent behavior across browsers 
- Phewas plot:
- update margins
- edit therapeutic area labels so shorter (after discussion with @d0choa)
- fix bug with uncategorised values in PheWas plot
- add legend
**Issue:** [#3537](https://github.com/opentargets/issues/issues/3537), [#3502](https://github.com/opentargets/issues/issues/3502)
Checked no study and variant pages.
> [Platform]: Phewas and Manhattan plot fixes 

- packages/sections/src/constants.js
- packages/sections/src/credibleSet/MolQTLColoc/Body.tsx
- packages/sections/src/credibleSet/MolQTLColoc/MolQTLColocQuery.gql
- packages/sections/src/credibleSet/MolQTLColoc/MolQTLColocSummaryFragment.gql
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsQuery.gql
- packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
> [Platform]: QTL studytype in queries

- apps/platform/src/components/AssociationsToolkit/static_datasets/dataSourcesAssoc.js
- packages/sections/src/evidence/GWASCredibleSets/index.js
After some feedback from David H and discussion with @buniello, we want to rename the widget name for the more accessible `GWAS associations`
> refactor: rename gwas credible set datasource

- packages/sections/src/credibleSet/Variants/Body.tsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/InSilicoPredictors/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Use `toFixed` or `toPrecision` appropriately in numeric columns
**Issue:** [#3666](https://github.com/opentargets/issues/issues/3666)
Checked relevant pages
> [Platform]: Numeric precision

- packages/sections/src/variant/GWASCredibleSets/PheWasPlot.tsx
Fix credible set size in PheWas plot tooltip
Checked PheWas plot
> [Platform]: Fix credible set size in PheWas plot tooltip

- packages/sections/src/credibleSet/GWASColoc/Description.tsx
- packages/sections/src/credibleSet/Locus2Gene/Description.tsx
- packages/sections/src/credibleSet/MolQTLColoc/Description.tsx
- packages/sections/src/credibleSet/Variants/Description.tsx
- packages/sections/src/evidence/GWASCredibleSets/Description.jsx
- packages/sections/src/study/GWASCredibleSets/Description.tsx
- packages/sections/src/study/QTLCredibleSets/Description.tsx
- packages/sections/src/variant/GWASCredibleSets/Description.tsx
- packages/sections/src/variant/QTLCredibleSets/Description.tsx
Update open targets links in widget descriptions to point to merged product docs rather than homepage.
Checked relevant pages
> [Platform]: Update open targets links in widget descriptions

- packages/sections/src/credibleSet/Locus2Gene/Description.tsx
- packages/sections/src/variant/InSilicoPredictors/InSilicoPredictorsPlot.tsx
- Locus 2 gene widget description clarifies that it's an incomplete widget
- In silico predictors flags in the tooltip 2 method that are deprecated because their non-commercial license
> feat: some warnings  

- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/PheWasPlot.tsx
When lead variant is same as page variant, show variant id as plain text (not a link) with 'self' chip - as do in table.
Add unique key to PheWas plot to prevent widget crashing when follow lead variant link to another variant page.
Checked on variant page.
> [Platform]: Fix lead variant link from PheWas plot tooltip 

- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Use `toPrecision` for posterior probs in credible sets widgets on variant page - these variants are not the leads so can have tiny probs after all.
**Issue:** [#3666](https://github.com/opentargets/issues/issues/3666)
Checked on variant page
> [Platform]: Use toPrecision for posterior probabilities

- packages/sections/src/target/DepMap/DepmapPlot.jsx
Crosshairs in the depmap plot are not in font size 12 like the axes and the crosshairs do not have a fontsize option so I set the fontSize for the whole plot to also affect the crosshairs.
- Test A locally with yarn
> [Platform]: Set plot-wide fontSize to affect crosshair for DepmapPlot

- packages/sections/src/drug/Pharmacogenomics/PharmacogenomicsSummary.gql
- packages/sections/src/drug/Pharmacogenomics/Summary.jsx
- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsSummaryFragment.gql
- packages/sections/src/study/GWASCredibleSets/Summary.tsx
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
- packages/sections/src/study/QTLCredibleSets/Summary.tsx
- packages/sections/src/target/Pharmacogenomics/PharmacogenomicsSummary.gql
- packages/sections/src/target/Pharmacogenomics/Summary.jsx
- packages/sections/src/variant/GWASCredibleSets/GWASCredibleSetsSummaryFragment.gql
- packages/sections/src/variant/GWASCredibleSets/Summary.tsx
- packages/sections/src/variant/Pharmacogenomics/PharmacogenomicsSummaryFragment.gql
- packages/sections/src/variant/Pharmacogenomics/Summary.tsx
- packages/sections/src/variant/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
- packages/sections/src/variant/QTLCredibleSets/Summary.tsx
Updating duplicate fragment name and removing console warnings.
**Deploy preview:** https://deploy-preview-626--ot-platform-partner.netlify.app/
- Test A
- Test B
> [Platform]: duplicate fragment name updates

- apps/platform/src/components/Search/SearchQuery.gql
- apps/platform/src/pages/SearchPage/SearchContainer.jsx
- apps/platform/src/pages/SearchPage/SearchPageQuery.gql
- apps/platform/src/pages/SearchPage/StudyResult.jsx
- packages/ui/src/components/GlobalSearch/GlobalSearchDialog.jsx
- packages/ui/src/components/GlobalSearch/GlobalSearchListHeader.jsx
- packages/ui/src/components/GlobalSearch/GlobalSearchListItem.jsx
- packages/ui/src/components/GlobalSearch/utils/searchUtils.js
- packages/ui/src/hooks/useListOption.js
**Issue:** https://github.com/opentargets/issues/issues/3561
- Test A
- Test B
> [Platform]: Adding search by study to platform

- apps/platform/src/components/Search/SearchQuery.gql
- apps/platform/src/pages/SearchPage/SearchPageQuery.gql
- apps/platform/src/pages/SearchPage/StudyResult.jsx
- apps/platform/src/pages/StudyPage/Profile.tsx
- apps/platform/src/pages/StudyPage/StudyProfileHeader.gql
- packages/sections/src/study/GWASCredibleSets/GWASCredibleSetsSummaryFragment.gql
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
- packages/ui/src/components/GlobalSearch/GlobalSearchListHeader.jsx
- packages/ui/src/components/GlobalSearch/GlobalSearchListItem.jsx
Long id ellipsis fix in global search 
- Test A
- Test B
> [Platform]: Long id ellipsis

- apps/platform/src/components/Search/SearchQuery.gql
- apps/platform/src/pages/SearchPage/SearchPageQuery.gql
- apps/platform/src/pages/SearchPage/StudyResult.jsx
- packages/ui/src/components/GlobalSearch/GlobalSearchListItem.jsx
**Issue:** https://github.com/opentargets/issues/issues/3561#issuecomment-2637302023
- Test A
- Test B
> [Platform]: study search ui label change

- apps/platform/src/pages/HomePage/HomePage.jsx
- apps/platform/src/pages/HomePage/searchExamples.ts
- apps/platform/src/utils/global.ts
Added homepage study suggestions 
- Added study suggestions for homepage
- Change variant suggestions count from 3 to 2 
- Updating examples array to common one to remove ppp examples vs public examples.
**Issue:** https://github.com/opentargets/issues/issues/3764
- Test A
- Test B
> [Platform]: Homepage study suggestions

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/MolQTLColoc/Body.tsx
As suggested by @xyg123, tooltip to explain CLPP column in the two colocalisation widgets:
> [Platform]: feat clpp column tooltip

- packages/sections/src/variant/Pharmacogenomics/Body.tsx
- packages/sections/src/variant/Pharmacogenomics/PharmacogenomicsQuery.gql
Add gene column to pgx widget on variant page.
**Issue:** [3792](https://github.com/opentargets/issues/issues/3792)
> [Platform]: Add gene column to pgx widget on variant page

- apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx
- packages/sections/src/evidence/GWASCredibleSets/Body.jsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Fixes the above typo (should be linkage-**_disequilibrium_**) in the confidence tooltip.
> [Platform]: fix ld typo in credible set confidence tooltip

- apps/platform/src/pages/StudyPage/Header.tsx
- packages/sections/src/disease/GWASStudies/Description.tsx
- packages/sections/src/study/SharedTraitStudies/Description.tsx
Fix study page profile for FinnGen studies.
Also update FinnGen links to R12. (This is expected to be the last FinGenn release so should not be an ongoing issue.)
**Issue:** [#3789](https://github.com/opentargets/issues/issues/3789)
> [Platform]: Fix study page profile for FinnGen studies

- packages/sections/src/credibleSet/GWASColoc/Body.tsx
- packages/sections/src/credibleSet/MolQTLColoc/Body.tsx
- packages/sections/src/evidence/GWASCredibleSets/Body.jsx
- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/GWASCredibleSets/ManhattanPlot.tsx
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/PheWasPlot.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
Harmonise credible set navigate and L2G score columns.
Also change L2G score in Manhattan and PheWas plots from bar to number.
> [Platform] Harmonise credible set navigate and L2G score columns

- packages/ui/src/components/HeatmapTable/HeatmapTable.tsx
Explicitly set a non-empty x domain when waterfall plot has only zero-length bars.
**Issue:** [#3793](https://github.com/opentargets/issues/issues/3793)
Checked on dev
> [Platform] L2G waterfall plot - handle when all bars have zero length

- packages/ui/src/components/HeatmapTable/L2GScoreIndicator.tsx
L2GScoreIndicator updates:
- Anchor popover on right. Prevents cases where popover on extreme right of window caused reduced width and crushed table cells. I think anchoring right also looks better, but does hide more content of the table.
- Use a min-width - behaves as expected with change to anchoring
- Fix invalid anchor property
- Include legend in popover heatmap
- Use numeric font and right-alignment in L2G score column for consistency with other numeric columns.
Checked on dev
> [Platform]: L2GScoreIndicator updates

- packages/sections/src/study/GWASCredibleSets/ManhattanPlot.tsx
- packages/sections/src/variant/GWASCredibleSets/PheWasPlot.tsx
Update navigate to credible set row in PheWas and Manhattan plot tooltips. (A previous PR updated the L2G score row in the tooltips but not the first row.)
> [Platform]: Update navigate to credible set row in plot tooltips

- packages/sections/src/drug/AdverseEvents/Body.jsx
Fix font size in pharmacovigilance table.
Checked on dev
> [Platform]: Fix font size in pharmacovigilance table

- apps/platform/src/pages/CredibleSetPage/ProfileHeader.tsx
- apps/platform/src/pages/SearchPage/SearchContainer.jsx
- apps/platform/src/pages/SearchPage/StudyResult.jsx
- apps/platform/src/pages/StudyPage/StudyProfileHeader.tsx
- packages/ui/src/components/GlobalSearch/GlobalSearchListItem.jsx
- packages/ui/src/components/Navigate.tsx
- packages/ui/src/components/OtAsyncTooltip/OtAsyncTooltip.tsx
- packages/ui/src/components/OtAsyncTooltip/queries/CredibleSetsTooltipQuery.gql
- packages/ui/src/components/OtAsyncTooltip/queries/StudyTooltipQuery.gql
- packages/ui/src/components/OtAsyncTooltip/utils/asyncTooltipUtil.ts
- packages/ui/src/components/StudyPublication.tsx
- packages/ui/src/index.tsx
**Issue:** https://github.com/opentargets/issues/issues/3763#issuecomment-2697612716
**Deploy preview:** https://deploy-preview-694--ot-platform.netlify.app/
- Test A
- Test B
> [Platform]: cs async tooltip and study author

- packages/sections/src/disease/GWASStudies/Body.tsx
Make GWAS Studies on disease page the same as Shared Trait Studies on study page (Look publication column on Shared Trait Studies)
- Test A
- Test B
> [Platform]: publication column

- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/QTLCredibleSetsQuery.gql
Add finemapping confidence column to qtl credible sets on study page.
Also fix sorting on this column to use number of stars rather than confidence string.
> [Platform] Add finemapping confidence column to qtl credible sets on study page

- .github/workflows/image.yaml
- .github/workflows/publish.yaml
- apps/platform/Dockerfile
- apps/platform/etc/entrypoint.sh
This PR changes the new build process so the configuration is passed as env vars to the `Dockerfile`. Currently we're writing the config in the GitHub action using arguments, but this is not flexible enough if we would like to build outside of GitHub. The benefit is we don't have to build two images anymore, as the specific web app config can be passed using env vars in the deployment process for platform/ppp.
None apply, this PR is related to workflow automation.
There is a working run of the ci/cd pipelines [in my fork](https://github.com/javfg/ot-ui-apps/actions/runs/13867640578), and a [new image](https://github.com/javfg/ot-ui-apps/pkgs/container/ot-ui-apps%2Fot-ui-apps) with platform-specific config.
> [AppConfig] environment variable based config

- packages/sections/src/credibleSet/Variants/Body.tsx
Credible set variants widget - sort lead variant higher if posteriors tie.
**Issue:** [#3794](https://github.com/opentargets/issues/issues/3794)
> [Platform]: Credible set variants widget - sort lead variant higher if posteriors tie

- packages/sections/src/study/GWASCredibleSets/Body.tsx
- packages/sections/src/study/QTLCredibleSets/Body.tsx
- packages/sections/src/variant/GWASCredibleSets/Body.tsx
- packages/sections/src/variant/QTLCredibleSets/Body.tsx
- packages/ui/src/components/HeatmapTable/HeatmapLegend.tsx
Add links to tooltips - confidence columns and L2G heatmap legend
Checked on dev
> [Platform]: Add links to tooltips - confidence columns and L2G heatmap legend

- packages/sections/src/variant/GWASCredibleSets/Body.tsx
re-oredring conditions to handle null case
**Issue:** https://github.com/opentargets/issues/issues/3869
**Deploy preview:** https://deploy-preview-731--ot-platform.netlify.app/variant/2_59928185_A_T
- Test A:  Go to https://platform.opentargets.org/variant/2_59928185_A_T gwas cred widget is crashing
- Test B:  Go to https://deploy-preview-731--ot-platform.netlify.app/variant/2_59928185_A_T gwas cred widget should not crash
> [Platform]: re-oredring conditions to handle null case

- packages/ot-constants/src/index.ts
**Issue:** [#3872](https://github.com/opentargets/issues/issues/3872)
> [Platform] Fixed typo in population ancestry description

- apps/platform/src/pages/DownloadsPage/ContainedInDrawer.tsx
Because the paths have changed, the level of directory that we want to download is different now.
This is causing the directory contents to be downloaded instead of the directory itself
> fix:wrong level of nested path

- .github/workflows/build.yaml
- .github/workflows/image.yaml
- .github/workflows/publish.yaml
- package.json
Approximately a month ago we (@carcruz @jdhayhurst) discussed about the best option to provide the data files the frontend needs for its build process (disease_efo and the croissant). I'm going to summarize here because some time has passed.
* We have to provide defaults so anybody can build the frontend
* We need to authenticate in GCP to pull the latest files for our own builds
* We shouldn't tie the frontend repo to a data release, because although web is usually dependent on one, we have multiple test runs and each would require a change in the frontend (imagine 25.06-testrun-1, 2, etc).
The best idea right now is to provide those two data files in the repo itself as defaults (as we currently do already), and pass a Google Cloud bucket as an argument to the build workflow, that, if …
> [AppConfig] input-based manual release

- packages/sections/src/drug/Pharmacogenomics/Body.jsx
- packages/sections/src/drug/Pharmacogenomics/Pharmacogenomics.gql
- packages/sections/src/target/Pharmacogenomics/Body.jsx
- packages/sections/src/target/Pharmacogenomics/Pharmacogenomics.gql
- packages/sections/src/variant/Pharmacogenomics/Body.tsx
- packages/sections/src/variant/Pharmacogenomics/PharmacogenomicsQuery.gql
- packages/ui/src/components/DirectionalityDrawer.tsx
- packages/ui/src/index.tsx
Added a common component for directionality drawer to show the contents
**Issue:** https://github.com/opentargets/issues/issues/3913
**Deploy preview:** https://deploy-preview-759--ot-platform.netlify.app/
- Test A
- Test B
> [Platform]: Adding a new column+drawer to Pharmacogenetics widgets to visualise new variant annotation dataset

- packages/ui/src/components/AlphaFoldPathogenicityLegend.tsx
[Platform]: Fix text alignment in pathogenicity legend
**Issue:** [#3840](https://github.com/opentargets/issues/issues/3840)
**Deploy preview:** https://deploy-preview-770--ot-platform.netlify.app/
Checked on dev
> [Platform]: Fix text alignment in pathogenicity legend

- packages/sections/src/variant/MolecularStructure/Viewer.tsx
Add variant label to variant page structure viewer.
**Issue:** [#3840](https://github.com/opentargets/issues/issues/3840)
**Deploy preview:** https://deploy-preview-780--ot-platform.netlify.app/variant/12_25245350_C_T
> [Platform]: Add variant label to variant page structure viewer

- packages/sections/src/variant/MolecularStructure/MolecularStructureSummaryFragment.gql
- packages/sections/src/variant/MolecularStructure/Viewer.tsx
- packages/sections/src/variant/MolecularStructure/index.ts
**Not ready for merge as there ongoing discussions on this issue.**
Hide variant page structure viewer if reference amino acid starts with a dash.
**Issue:** [#3840](https://github.com/opentargets/issues/issues/3840)
**Deploy preview:** https://deploy-preview-779--ot-platform.netlify.app/variant/12_25245375_A_AT
> [Platform]: Hide variant page structure viewer if reference amino acid starts with a dash

- apps/platform/etc/platform.conf
This PR adds a configuration to the nginx server that redirects requests for the deprecated genetics app into the new merged platform. It appends a `from=genetics` queryparam so the frontend can notify users.
Pending work: showing that modal dialog with information when coming from a redirection.
**Issue:** https://github.com/opentargets/issues/issues/3881
**Deploy preview:** https://genetics-dev.opentargets.org
Test URLs:
home: https://genetics-dev.opentargets.org
a variant: https://genetics-dev.opentargets.org/variant/1_154453788_C_T
a study: https://genetics-dev.opentargets.org/Study/GCST010340
a gene: https://genetics-dev.opentargets.org/gene/ENSG00000169174   (/gene/ becomes /target/)
a study that no longer exists: https://genetics.opentargets.org/study/GCST002222
> [AppConfig]: Genetics redirection

- packages/ot-constants/src/index.ts
Removed the link to Open Targets Genetics from the list of external links included in the Platform footer. 
**Issue:** ([link](https://github.com/opentargets/issues/issues/3989))
Previewed the changes on my local; the link was no longer there.
> [Platform]: Removing link for OTG in Platform footer

- .github/workflows/image.yaml
The docker image in GHCR is being named incorrectly: `ghcr.io/opentargets/ot-ui-apps/ot-ui-apps`. This PR fixes the naming so it is `ghcr.io/opentargets/ot-ui-apps`.
> [AppConfig] Fix GHCR image name

- packages/sections/src/evidence/Gene2Phenotype/Body.jsx
- packages/sections/src/evidence/Gene2Phenotype/sectionQuery.gql
This PR fixes the Gene2Phenotype links in the evidence section to use the correct URL format.
- Updated `g2pUrl` function to use the correct query parameter format
- Removed unnecessary `studyId` and `symbol` parameters from the function
- Now properly passes `targetFromSourceId` and `diseaseFromSource` to build the search URL
- Fixed URL format from `?panel=DD&search_term=FGFR3` to `?query=-related%20`
The links now generate URLs in the expected format:
- **Before**: `https://www.ebi.ac.uk/gene2phenotype/search?panel=DD&search_term=FGFR3`
- **After**: `https://www.ebi.ac.uk/gene2phenotype/search?query=-related%20`
Resolves https://github.com/opentargets/issues/issues/3831
> [Platform]: correct Gene2Phenotype links to use proper query format

- apps/platform/src/components/AssociationsToolkit/static_datasets/prioritisationColumns.ts
- apps/platform/src/pages/APIPage/APIPage.jsx
- packages/sections/src/credibleSet/GWASColoc/Description.tsx
- packages/sections/src/credibleSet/Locus2Gene/Description.tsx
- packages/sections/src/credibleSet/Locus2Gene/index.ts
- packages/sections/src/disease/GWASStudies/Description.tsx
- packages/sections/src/disease/GWASStudies/index.ts
- packages/sections/src/study/SharedTraitStudies/Description.tsx
- packages/sections/src/target/ComparativeGenomics/ComparativeGenomicsPlot.tsx
This PR addresses all the UI consistency issues identified in [GitHub issue #3868](https://github.com/opentargets/issues/issues/3868) to align with the Open Targets style guide.
@HelenaCornu GWAS studies I could do a few but there are cases in which is quite tricky. It's complicated. We use GWAS studies as a coined term to distinguish against molQTL studies. However they are technically both GWAS. There was some discussion around this in the early days of gentropy with Yakov and we concluded to stick to this nomenclature. It's however true the `S` in GWAS refers to studies but it would be very weird to have a `GWAS` widget in the target page that excludes molQTL.
Each task is in a different commit in case we want to revert anything 
- **File**: …
> [Platform]: UI consistency updates for Open Targets style guide

- apps/platform/.env
- apps/platform/src/pages/TargetPage/Profile.tsx
- apps/platform/src/sections/targetSections.ts
- packages/sections/src/target/QTLCredibleSets/Body.tsx
- packages/sections/src/target/QTLCredibleSets/Description.tsx
- packages/sections/src/target/QTLCredibleSets/QTLCredibleSetsQuery.gql
- packages/sections/src/target/QTLCredibleSets/QTLCredibleSetsSummaryFragment.gql
- packages/sections/src/target/QTLCredibleSets/Summary.tsx
- packages/sections/src/target/QTLCredibleSets/index.ts
- packages/sections/src/target/index.ts
Add molQTL credible sets widget to target page.
**Issue:** [#3892](https://github.com/opentargets/issues/issues/3892)
**Deploy preview:** https://deploy-preview-796--ot-platform-partner.netlify.app/target/ENSG00000136244
Checked on local.
> [Platform]: Add molQTL credible sets widget to target page

- apps/platform/src/pages/DrugPage/Smiles/SmilesHelper.jsx
Remove custom padding, which means the larger default padding is used - so text is less likely to be cropped.
Closes https://github.com/opentargets/issues/issues/3137
**Issue:** [#3137](https://github.com/opentargets/issues/issues/3137)
> [Platform]: Fix padding on smiles drawer on drug page

- packages/sections/src/target/MolecularStructure/Body.jsx
- packages/sections/src/target/MolecularStructure/Table.tsx
- packages/sections/src/target/MolecularStructure/helpers.ts
Target page structure viewer: The widget table is populated from a request to `https://www.ebi.ac.uk/proteins/api/proteins/` but this no longer works. This PR updates the request to use `rest.uniprot.org/uniprotkb/` and processes the results into the format expected by the widget.
**Issue:** Fixes [#4081](https://github.com/opentargets/issues/issues/4081)
**Deploy preview:** https://deploy-preview-825--ot-platform.netlify.app/target/ENSG00000133703
> [Platform]: Target page structure viewer - fetch results list from uniprot
